/*
Aptible API v1

REST API for the core Aptible platform.

API version: v1
Contact: support@aptible.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// IntrusionDetectionReportsAPIService IntrusionDetectionReportsAPI service
type IntrusionDetectionReportsAPIService service

type ApiGetIntrustionDetectionReportRequest struct {
	ctx context.Context
	ApiService *IntrusionDetectionReportsAPIService
	id int32
	noEmbed *bool
	prefer *string
}

// When true, omits embedded resources from the response. Also triggered when the Prefer: no_sensitive_extras&#x3D;true header is present.
func (r ApiGetIntrustionDetectionReportRequest) NoEmbed(noEmbed bool) ApiGetIntrustionDetectionReportRequest {
	r.noEmbed = &noEmbed
	return r
}

// When set to no_sensitive_extras&#x3D;true, omits sensitive fields and embedded resources from the response.
func (r ApiGetIntrustionDetectionReportRequest) Prefer(prefer string) ApiGetIntrustionDetectionReportRequest {
	r.prefer = &prefer
	return r
}

func (r ApiGetIntrustionDetectionReportRequest) Execute() (*IntrusionDetectionReport, *http.Response, error) {
	return r.ApiService.GetIntrustionDetectionReportExecute(r)
}

/*
GetIntrustionDetectionReport show intrusion_detection_report

Returns the details of a specific intrusion detection report by ID.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id id
 @return ApiGetIntrustionDetectionReportRequest
*/
func (a *IntrusionDetectionReportsAPIService) GetIntrustionDetectionReport(ctx context.Context, id int32) ApiGetIntrustionDetectionReportRequest {
	return ApiGetIntrustionDetectionReportRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return IntrusionDetectionReport
func (a *IntrusionDetectionReportsAPIService) GetIntrustionDetectionReportExecute(r ApiGetIntrustionDetectionReportRequest) (*IntrusionDetectionReport, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *IntrusionDetectionReport
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IntrusionDetectionReportsAPIService.GetIntrustionDetectionReport")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/intrusion_detection_reports/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.noEmbed != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "no_embed", r.noEmbed, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/hal+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.prefer != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Prefer", r.prefer, "simple", "")
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["token"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ModelError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetIntrustionDetectionReportCsvDownloadRequest struct {
	ctx context.Context
	ApiService *IntrusionDetectionReportsAPIService
	intrusionReportId int32
	noEmbed *bool
	prefer *string
}

// When true, omits embedded resources from the response. Also triggered when the Prefer: no_sensitive_extras&#x3D;true header is present.
func (r ApiGetIntrustionDetectionReportCsvDownloadRequest) NoEmbed(noEmbed bool) ApiGetIntrustionDetectionReportCsvDownloadRequest {
	r.noEmbed = &noEmbed
	return r
}

// When set to no_sensitive_extras&#x3D;true, omits sensitive fields and embedded resources from the response.
func (r ApiGetIntrustionDetectionReportCsvDownloadRequest) Prefer(prefer string) ApiGetIntrustionDetectionReportCsvDownloadRequest {
	r.prefer = &prefer
	return r
}

func (r ApiGetIntrustionDetectionReportCsvDownloadRequest) Execute() (*http.Response, error) {
	return r.ApiService.GetIntrustionDetectionReportCsvDownloadExecute(r)
}

/*
GetIntrustionDetectionReportCsvDownload download_csv intrusion_detection_report

Returns a presigned URL to download the intrusion detection report as CSV.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param intrusionReportId intrusion_report_id
 @return ApiGetIntrustionDetectionReportCsvDownloadRequest
*/
func (a *IntrusionDetectionReportsAPIService) GetIntrustionDetectionReportCsvDownload(ctx context.Context, intrusionReportId int32) ApiGetIntrustionDetectionReportCsvDownloadRequest {
	return ApiGetIntrustionDetectionReportCsvDownloadRequest{
		ApiService: a,
		ctx: ctx,
		intrusionReportId: intrusionReportId,
	}
}

// Execute executes the request
func (a *IntrusionDetectionReportsAPIService) GetIntrustionDetectionReportCsvDownloadExecute(r ApiGetIntrustionDetectionReportCsvDownloadRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IntrusionDetectionReportsAPIService.GetIntrustionDetectionReportCsvDownload")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/intrusion_detection_reports/{intrusion_report_id}/download_csv"
	localVarPath = strings.Replace(localVarPath, "{"+"intrusion_report_id"+"}", url.PathEscape(parameterValueToString(r.intrusionReportId, "intrusionReportId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.noEmbed != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "no_embed", r.noEmbed, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/hal+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.prefer != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Prefer", r.prefer, "simple", "")
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["token"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ModelError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetIntrustionDetectionReportPdfDownloadRequest struct {
	ctx context.Context
	ApiService *IntrusionDetectionReportsAPIService
	intrusionReportId int32
	noEmbed *bool
	prefer *string
}

// When true, omits embedded resources from the response. Also triggered when the Prefer: no_sensitive_extras&#x3D;true header is present.
func (r ApiGetIntrustionDetectionReportPdfDownloadRequest) NoEmbed(noEmbed bool) ApiGetIntrustionDetectionReportPdfDownloadRequest {
	r.noEmbed = &noEmbed
	return r
}

// When set to no_sensitive_extras&#x3D;true, omits sensitive fields and embedded resources from the response.
func (r ApiGetIntrustionDetectionReportPdfDownloadRequest) Prefer(prefer string) ApiGetIntrustionDetectionReportPdfDownloadRequest {
	r.prefer = &prefer
	return r
}

func (r ApiGetIntrustionDetectionReportPdfDownloadRequest) Execute() (*http.Response, error) {
	return r.ApiService.GetIntrustionDetectionReportPdfDownloadExecute(r)
}

/*
GetIntrustionDetectionReportPdfDownload download_pdf intrusion_detection_report

Returns a presigned URL to download the intrusion detection report as PDF.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param intrusionReportId intrusion_report_id
 @return ApiGetIntrustionDetectionReportPdfDownloadRequest
*/
func (a *IntrusionDetectionReportsAPIService) GetIntrustionDetectionReportPdfDownload(ctx context.Context, intrusionReportId int32) ApiGetIntrustionDetectionReportPdfDownloadRequest {
	return ApiGetIntrustionDetectionReportPdfDownloadRequest{
		ApiService: a,
		ctx: ctx,
		intrusionReportId: intrusionReportId,
	}
}

// Execute executes the request
func (a *IntrusionDetectionReportsAPIService) GetIntrustionDetectionReportPdfDownloadExecute(r ApiGetIntrustionDetectionReportPdfDownloadRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IntrusionDetectionReportsAPIService.GetIntrustionDetectionReportPdfDownload")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/intrusion_detection_reports/{intrusion_report_id}/download_pdf"
	localVarPath = strings.Replace(localVarPath, "{"+"intrusion_report_id"+"}", url.PathEscape(parameterValueToString(r.intrusionReportId, "intrusionReportId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.noEmbed != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "no_embed", r.noEmbed, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/hal+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.prefer != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Prefer", r.prefer, "simple", "")
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["token"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ModelError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiListIntrustionDetectionReportsForStackRequest struct {
	ctx context.Context
	ApiService *IntrusionDetectionReportsAPIService
	stackId int32
	page *int32
	perPage *int32
	noEmbed *bool
	prefer *string
}

// Current page of paginated results
func (r ApiListIntrustionDetectionReportsForStackRequest) Page(page int32) ApiListIntrustionDetectionReportsForStackRequest {
	r.page = &page
	return r
}

// Number of results to return per page
func (r ApiListIntrustionDetectionReportsForStackRequest) PerPage(perPage int32) ApiListIntrustionDetectionReportsForStackRequest {
	r.perPage = &perPage
	return r
}

// When true, omits embedded resources from the response. Also triggered when the Prefer: no_sensitive_extras&#x3D;true header is present.
func (r ApiListIntrustionDetectionReportsForStackRequest) NoEmbed(noEmbed bool) ApiListIntrustionDetectionReportsForStackRequest {
	r.noEmbed = &noEmbed
	return r
}

// When set to no_sensitive_extras&#x3D;true, omits sensitive fields and embedded resources from the response.
func (r ApiListIntrustionDetectionReportsForStackRequest) Prefer(prefer string) ApiListIntrustionDetectionReportsForStackRequest {
	r.prefer = &prefer
	return r
}

func (r ApiListIntrustionDetectionReportsForStackRequest) Execute() (*ListIntrustionDetectionReportsForStack200Response, *http.Response, error) {
	return r.ApiService.ListIntrustionDetectionReportsForStackExecute(r)
}

/*
ListIntrustionDetectionReportsForStack list intrusion_detection_reports

Returns a paginated list of intrusion detection reports for the specified stack.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param stackId stack_id
 @return ApiListIntrustionDetectionReportsForStackRequest
*/
func (a *IntrusionDetectionReportsAPIService) ListIntrustionDetectionReportsForStack(ctx context.Context, stackId int32) ApiListIntrustionDetectionReportsForStackRequest {
	return ApiListIntrustionDetectionReportsForStackRequest{
		ApiService: a,
		ctx: ctx,
		stackId: stackId,
	}
}

// Execute executes the request
//  @return ListIntrustionDetectionReportsForStack200Response
func (a *IntrusionDetectionReportsAPIService) ListIntrustionDetectionReportsForStackExecute(r ApiListIntrustionDetectionReportsForStackRequest) (*ListIntrustionDetectionReportsForStack200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ListIntrustionDetectionReportsForStack200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IntrusionDetectionReportsAPIService.ListIntrustionDetectionReportsForStack")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/stacks/{stack_id}/intrusion_detection_reports"
	localVarPath = strings.Replace(localVarPath, "{"+"stack_id"+"}", url.PathEscape(parameterValueToString(r.stackId, "stackId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "form", "")
	}
	if r.perPage != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "per_page", r.perPage, "form", "")
	}
	if r.noEmbed != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "no_embed", r.noEmbed, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/hal+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.prefer != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Prefer", r.prefer, "simple", "")
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["token"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ModelError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
