/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the AccountLinksApps type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountLinksApps{}

// AccountLinksApps struct for AccountLinksApps
type AccountLinksApps struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AccountLinksApps AccountLinksApps

// NewAccountLinksApps instantiates a new AccountLinksApps object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountLinksApps() *AccountLinksApps {
	this := AccountLinksApps{}
	return &this
}

// NewAccountLinksAppsWithDefaults instantiates a new AccountLinksApps object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountLinksAppsWithDefaults() *AccountLinksApps {
	this := AccountLinksApps{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *AccountLinksApps) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountLinksApps) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *AccountLinksApps) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *AccountLinksApps) SetHref(v string) {
	o.Href = &v
}

func (o AccountLinksApps) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountLinksApps) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccountLinksApps) UnmarshalJSON(data []byte) (err error) {
	varAccountLinksApps := _AccountLinksApps{}

	err = json.Unmarshal(data, &varAccountLinksApps)

	if err != nil {
		return err
	}

	*o = AccountLinksApps(varAccountLinksApps)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccountLinksApps struct {
	value *AccountLinksApps
	isSet bool
}

func (v NullableAccountLinksApps) Get() *AccountLinksApps {
	return v.value
}

func (v *NullableAccountLinksApps) Set(val *AccountLinksApps) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountLinksApps) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountLinksApps) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountLinksApps(val *AccountLinksApps) *NullableAccountLinksApps {
	return &NullableAccountLinksApps{value: val, isSet: true}
}

func (v NullableAccountLinksApps) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountLinksApps) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


