/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded{}

// ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded struct for ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded
type ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded struct {
	ExternalAwsResources []ExternalAwsResource `json:"external_aws_resources,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded

// NewListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded instantiates a new ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded() *ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded {
	this := ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded{}
	return &this
}

// NewListExternalAwsResourcesForExternalAwsAccount200ResponseEmbeddedWithDefaults instantiates a new ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListExternalAwsResourcesForExternalAwsAccount200ResponseEmbeddedWithDefaults() *ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded {
	this := ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded{}
	return &this
}

// GetExternalAwsResources returns the ExternalAwsResources field value if set, zero value otherwise.
func (o *ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) GetExternalAwsResources() []ExternalAwsResource {
	if o == nil || IsNil(o.ExternalAwsResources) {
		var ret []ExternalAwsResource
		return ret
	}
	return o.ExternalAwsResources
}

// GetExternalAwsResourcesOk returns a tuple with the ExternalAwsResources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) GetExternalAwsResourcesOk() ([]ExternalAwsResource, bool) {
	if o == nil || IsNil(o.ExternalAwsResources) {
		return nil, false
	}
	return o.ExternalAwsResources, true
}

// HasExternalAwsResources returns a boolean if a field has been set.
func (o *ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) HasExternalAwsResources() bool {
	if o != nil && !IsNil(o.ExternalAwsResources) {
		return true
	}

	return false
}

// SetExternalAwsResources gets a reference to the given []ExternalAwsResource and assigns it to the ExternalAwsResources field.
func (o *ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) SetExternalAwsResources(v []ExternalAwsResource) {
	o.ExternalAwsResources = v
}

func (o ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExternalAwsResources) {
		toSerialize["external_aws_resources"] = o.ExternalAwsResources
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) UnmarshalJSON(data []byte) (err error) {
	varListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded := _ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded{}

	err = json.Unmarshal(data, &varListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded)

	if err != nil {
		return err
	}

	*o = ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded(varListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "external_aws_resources")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded struct {
	value *ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded
	isSet bool
}

func (v NullableListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) Get() *ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded {
	return v.value
}

func (v *NullableListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) Set(val *ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) {
	v.value = val
	v.isSet = true
}

func (v NullableListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) IsSet() bool {
	return v.isSet
}

func (v *NullableListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded(val *ListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) *NullableListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded {
	return &NullableListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded{value: val, isSet: true}
}

func (v NullableListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListExternalAwsResourcesForExternalAwsAccount200ResponseEmbedded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


