/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListDatadogIntegrations200ResponseLinksNext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDatadogIntegrations200ResponseLinksNext{}

// ListDatadogIntegrations200ResponseLinksNext struct for ListDatadogIntegrations200ResponseLinksNext
type ListDatadogIntegrations200ResponseLinksNext struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListDatadogIntegrations200ResponseLinksNext ListDatadogIntegrations200ResponseLinksNext

// NewListDatadogIntegrations200ResponseLinksNext instantiates a new ListDatadogIntegrations200ResponseLinksNext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDatadogIntegrations200ResponseLinksNext() *ListDatadogIntegrations200ResponseLinksNext {
	this := ListDatadogIntegrations200ResponseLinksNext{}
	return &this
}

// NewListDatadogIntegrations200ResponseLinksNextWithDefaults instantiates a new ListDatadogIntegrations200ResponseLinksNext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDatadogIntegrations200ResponseLinksNextWithDefaults() *ListDatadogIntegrations200ResponseLinksNext {
	this := ListDatadogIntegrations200ResponseLinksNext{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListDatadogIntegrations200ResponseLinksNext) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDatadogIntegrations200ResponseLinksNext) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListDatadogIntegrations200ResponseLinksNext) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListDatadogIntegrations200ResponseLinksNext) SetHref(v string) {
	o.Href = &v
}

func (o ListDatadogIntegrations200ResponseLinksNext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDatadogIntegrations200ResponseLinksNext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListDatadogIntegrations200ResponseLinksNext) UnmarshalJSON(data []byte) (err error) {
	varListDatadogIntegrations200ResponseLinksNext := _ListDatadogIntegrations200ResponseLinksNext{}

	err = json.Unmarshal(data, &varListDatadogIntegrations200ResponseLinksNext)

	if err != nil {
		return err
	}

	*o = ListDatadogIntegrations200ResponseLinksNext(varListDatadogIntegrations200ResponseLinksNext)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListDatadogIntegrations200ResponseLinksNext struct {
	value *ListDatadogIntegrations200ResponseLinksNext
	isSet bool
}

func (v NullableListDatadogIntegrations200ResponseLinksNext) Get() *ListDatadogIntegrations200ResponseLinksNext {
	return v.value
}

func (v *NullableListDatadogIntegrations200ResponseLinksNext) Set(val *ListDatadogIntegrations200ResponseLinksNext) {
	v.value = val
	v.isSet = true
}

func (v NullableListDatadogIntegrations200ResponseLinksNext) IsSet() bool {
	return v.isSet
}

func (v *NullableListDatadogIntegrations200ResponseLinksNext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDatadogIntegrations200ResponseLinksNext(val *ListDatadogIntegrations200ResponseLinksNext) *NullableListDatadogIntegrations200ResponseLinksNext {
	return &NullableListDatadogIntegrations200ResponseLinksNext{value: val, isSet: true}
}

func (v NullableListDatadogIntegrations200ResponseLinksNext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDatadogIntegrations200ResponseLinksNext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


