/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain{}

// ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain struct for ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain
type ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain

// NewListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain instantiates a new ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain() *ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain {
	this := ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain{}
	return &this
}

// NewListEphemeralContainersForEphemeralSession200ResponseLinksLogDrainWithDefaults instantiates a new ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListEphemeralContainersForEphemeralSession200ResponseLinksLogDrainWithDefaults() *ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain {
	this := ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) SetHref(v string) {
	o.Href = &v
}

func (o ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) UnmarshalJSON(data []byte) (err error) {
	varListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain := _ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain{}

	err = json.Unmarshal(data, &varListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain)

	if err != nil {
		return err
	}

	*o = ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain(varListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain struct {
	value *ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain
	isSet bool
}

func (v NullableListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) Get() *ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain {
	return v.value
}

func (v *NullableListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) Set(val *ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) {
	v.value = val
	v.isSet = true
}

func (v NullableListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) IsSet() bool {
	return v.isSet
}

func (v *NullableListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain(val *ListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) *NullableListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain {
	return &NullableListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain{value: val, isSet: true}
}

func (v NullableListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListEphemeralContainersForEphemeralSession200ResponseLinksLogDrain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


