/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ObservationLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObservationLinks{}

// ObservationLinks struct for ObservationLinks
type ObservationLinks struct {
	Resource *ObservationLinksResource `json:"resource,omitempty"`
	Self *ObservationLinksSelf `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ObservationLinks ObservationLinks

// NewObservationLinks instantiates a new ObservationLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObservationLinks() *ObservationLinks {
	this := ObservationLinks{}
	return &this
}

// NewObservationLinksWithDefaults instantiates a new ObservationLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObservationLinksWithDefaults() *ObservationLinks {
	this := ObservationLinks{}
	return &this
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *ObservationLinks) GetResource() ObservationLinksResource {
	if o == nil || IsNil(o.Resource) {
		var ret ObservationLinksResource
		return ret
	}
	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObservationLinks) GetResourceOk() (*ObservationLinksResource, bool) {
	if o == nil || IsNil(o.Resource) {
		return nil, false
	}
	return o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *ObservationLinks) HasResource() bool {
	if o != nil && !IsNil(o.Resource) {
		return true
	}

	return false
}

// SetResource gets a reference to the given ObservationLinksResource and assigns it to the Resource field.
func (o *ObservationLinks) SetResource(v ObservationLinksResource) {
	o.Resource = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ObservationLinks) GetSelf() ObservationLinksSelf {
	if o == nil || IsNil(o.Self) {
		var ret ObservationLinksSelf
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObservationLinks) GetSelfOk() (*ObservationLinksSelf, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ObservationLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ObservationLinksSelf and assigns it to the Self field.
func (o *ObservationLinks) SetSelf(v ObservationLinksSelf) {
	o.Self = &v
}

func (o ObservationLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObservationLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Resource) {
		toSerialize["resource"] = o.Resource
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ObservationLinks) UnmarshalJSON(data []byte) (err error) {
	varObservationLinks := _ObservationLinks{}

	err = json.Unmarshal(data, &varObservationLinks)

	if err != nil {
		return err
	}

	*o = ObservationLinks(varObservationLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "resource")
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableObservationLinks struct {
	value *ObservationLinks
	isSet bool
}

func (v NullableObservationLinks) Get() *ObservationLinks {
	return v.value
}

func (v *NullableObservationLinks) Set(val *ObservationLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableObservationLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableObservationLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObservationLinks(val *ObservationLinks) *NullableObservationLinks {
	return &NullableObservationLinks{value: val, isSet: true}
}

func (v NullableObservationLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObservationLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


