/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListOperationsForDiskAttachment200ResponseLinksPrev type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOperationsForDiskAttachment200ResponseLinksPrev{}

// ListOperationsForDiskAttachment200ResponseLinksPrev struct for ListOperationsForDiskAttachment200ResponseLinksPrev
type ListOperationsForDiskAttachment200ResponseLinksPrev struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListOperationsForDiskAttachment200ResponseLinksPrev ListOperationsForDiskAttachment200ResponseLinksPrev

// NewListOperationsForDiskAttachment200ResponseLinksPrev instantiates a new ListOperationsForDiskAttachment200ResponseLinksPrev object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOperationsForDiskAttachment200ResponseLinksPrev() *ListOperationsForDiskAttachment200ResponseLinksPrev {
	this := ListOperationsForDiskAttachment200ResponseLinksPrev{}
	return &this
}

// NewListOperationsForDiskAttachment200ResponseLinksPrevWithDefaults instantiates a new ListOperationsForDiskAttachment200ResponseLinksPrev object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOperationsForDiskAttachment200ResponseLinksPrevWithDefaults() *ListOperationsForDiskAttachment200ResponseLinksPrev {
	this := ListOperationsForDiskAttachment200ResponseLinksPrev{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListOperationsForDiskAttachment200ResponseLinksPrev) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOperationsForDiskAttachment200ResponseLinksPrev) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListOperationsForDiskAttachment200ResponseLinksPrev) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListOperationsForDiskAttachment200ResponseLinksPrev) SetHref(v string) {
	o.Href = &v
}

func (o ListOperationsForDiskAttachment200ResponseLinksPrev) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOperationsForDiskAttachment200ResponseLinksPrev) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListOperationsForDiskAttachment200ResponseLinksPrev) UnmarshalJSON(data []byte) (err error) {
	varListOperationsForDiskAttachment200ResponseLinksPrev := _ListOperationsForDiskAttachment200ResponseLinksPrev{}

	err = json.Unmarshal(data, &varListOperationsForDiskAttachment200ResponseLinksPrev)

	if err != nil {
		return err
	}

	*o = ListOperationsForDiskAttachment200ResponseLinksPrev(varListOperationsForDiskAttachment200ResponseLinksPrev)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListOperationsForDiskAttachment200ResponseLinksPrev struct {
	value *ListOperationsForDiskAttachment200ResponseLinksPrev
	isSet bool
}

func (v NullableListOperationsForDiskAttachment200ResponseLinksPrev) Get() *ListOperationsForDiskAttachment200ResponseLinksPrev {
	return v.value
}

func (v *NullableListOperationsForDiskAttachment200ResponseLinksPrev) Set(val *ListOperationsForDiskAttachment200ResponseLinksPrev) {
	v.value = val
	v.isSet = true
}

func (v NullableListOperationsForDiskAttachment200ResponseLinksPrev) IsSet() bool {
	return v.isSet
}

func (v *NullableListOperationsForDiskAttachment200ResponseLinksPrev) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOperationsForDiskAttachment200ResponseLinksPrev(val *ListOperationsForDiskAttachment200ResponseLinksPrev) *NullableListOperationsForDiskAttachment200ResponseLinksPrev {
	return &NullableListOperationsForDiskAttachment200ResponseLinksPrev{value: val, isSet: true}
}

func (v NullableListOperationsForDiskAttachment200ResponseLinksPrev) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOperationsForDiskAttachment200ResponseLinksPrev) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


