/*
Aptible API v1

REST API for the core Aptible platform.

API version: v1
Contact: support@aptible.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateLlmGatewayConfigurationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLlmGatewayConfigurationRequest{}

// CreateLlmGatewayConfigurationRequest struct for CreateLlmGatewayConfigurationRequest
type CreateLlmGatewayConfigurationRequest struct {
	// The organization to enroll
	OrganizationId string `json:"organization_id"`
	AdditionalProperties map[string]interface{}
}

type _CreateLlmGatewayConfigurationRequest CreateLlmGatewayConfigurationRequest

// NewCreateLlmGatewayConfigurationRequest instantiates a new CreateLlmGatewayConfigurationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLlmGatewayConfigurationRequest(organizationId string) *CreateLlmGatewayConfigurationRequest {
	this := CreateLlmGatewayConfigurationRequest{}
	this.OrganizationId = organizationId
	return &this
}

// NewCreateLlmGatewayConfigurationRequestWithDefaults instantiates a new CreateLlmGatewayConfigurationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLlmGatewayConfigurationRequestWithDefaults() *CreateLlmGatewayConfigurationRequest {
	this := CreateLlmGatewayConfigurationRequest{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value
func (o *CreateLlmGatewayConfigurationRequest) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *CreateLlmGatewayConfigurationRequest) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *CreateLlmGatewayConfigurationRequest) SetOrganizationId(v string) {
	o.OrganizationId = v
}

func (o CreateLlmGatewayConfigurationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLlmGatewayConfigurationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organization_id"] = o.OrganizationId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateLlmGatewayConfigurationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organization_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateLlmGatewayConfigurationRequest := _CreateLlmGatewayConfigurationRequest{}

	err = json.Unmarshal(data, &varCreateLlmGatewayConfigurationRequest)

	if err != nil {
		return err
	}

	*o = CreateLlmGatewayConfigurationRequest(varCreateLlmGatewayConfigurationRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "organization_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateLlmGatewayConfigurationRequest struct {
	value *CreateLlmGatewayConfigurationRequest
	isSet bool
}

func (v NullableCreateLlmGatewayConfigurationRequest) Get() *CreateLlmGatewayConfigurationRequest {
	return v.value
}

func (v *NullableCreateLlmGatewayConfigurationRequest) Set(val *CreateLlmGatewayConfigurationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLlmGatewayConfigurationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLlmGatewayConfigurationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLlmGatewayConfigurationRequest(val *CreateLlmGatewayConfigurationRequest) *NullableCreateLlmGatewayConfigurationRequest {
	return &NullableCreateLlmGatewayConfigurationRequest{value: val, isSet: true}
}

func (v NullableCreateLlmGatewayConfigurationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLlmGatewayConfigurationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


