/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the UpdateAppExternalAwsRdsConnectionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAppExternalAwsRdsConnectionRequest{}

// UpdateAppExternalAwsRdsConnectionRequest struct for UpdateAppExternalAwsRdsConnectionRequest
type UpdateAppExternalAwsRdsConnectionRequest struct {
	DatabaseName *string `json:"database_name,omitempty"`
	DatabaseUser *string `json:"database_user,omitempty"`
	Superuser *bool `json:"superuser,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateAppExternalAwsRdsConnectionRequest UpdateAppExternalAwsRdsConnectionRequest

// NewUpdateAppExternalAwsRdsConnectionRequest instantiates a new UpdateAppExternalAwsRdsConnectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAppExternalAwsRdsConnectionRequest() *UpdateAppExternalAwsRdsConnectionRequest {
	this := UpdateAppExternalAwsRdsConnectionRequest{}
	return &this
}

// NewUpdateAppExternalAwsRdsConnectionRequestWithDefaults instantiates a new UpdateAppExternalAwsRdsConnectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAppExternalAwsRdsConnectionRequestWithDefaults() *UpdateAppExternalAwsRdsConnectionRequest {
	this := UpdateAppExternalAwsRdsConnectionRequest{}
	return &this
}

// GetDatabaseName returns the DatabaseName field value if set, zero value otherwise.
func (o *UpdateAppExternalAwsRdsConnectionRequest) GetDatabaseName() string {
	if o == nil || IsNil(o.DatabaseName) {
		var ret string
		return ret
	}
	return *o.DatabaseName
}

// GetDatabaseNameOk returns a tuple with the DatabaseName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAppExternalAwsRdsConnectionRequest) GetDatabaseNameOk() (*string, bool) {
	if o == nil || IsNil(o.DatabaseName) {
		return nil, false
	}
	return o.DatabaseName, true
}

// HasDatabaseName returns a boolean if a field has been set.
func (o *UpdateAppExternalAwsRdsConnectionRequest) HasDatabaseName() bool {
	if o != nil && !IsNil(o.DatabaseName) {
		return true
	}

	return false
}

// SetDatabaseName gets a reference to the given string and assigns it to the DatabaseName field.
func (o *UpdateAppExternalAwsRdsConnectionRequest) SetDatabaseName(v string) {
	o.DatabaseName = &v
}

// GetDatabaseUser returns the DatabaseUser field value if set, zero value otherwise.
func (o *UpdateAppExternalAwsRdsConnectionRequest) GetDatabaseUser() string {
	if o == nil || IsNil(o.DatabaseUser) {
		var ret string
		return ret
	}
	return *o.DatabaseUser
}

// GetDatabaseUserOk returns a tuple with the DatabaseUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAppExternalAwsRdsConnectionRequest) GetDatabaseUserOk() (*string, bool) {
	if o == nil || IsNil(o.DatabaseUser) {
		return nil, false
	}
	return o.DatabaseUser, true
}

// HasDatabaseUser returns a boolean if a field has been set.
func (o *UpdateAppExternalAwsRdsConnectionRequest) HasDatabaseUser() bool {
	if o != nil && !IsNil(o.DatabaseUser) {
		return true
	}

	return false
}

// SetDatabaseUser gets a reference to the given string and assigns it to the DatabaseUser field.
func (o *UpdateAppExternalAwsRdsConnectionRequest) SetDatabaseUser(v string) {
	o.DatabaseUser = &v
}

// GetSuperuser returns the Superuser field value if set, zero value otherwise.
func (o *UpdateAppExternalAwsRdsConnectionRequest) GetSuperuser() bool {
	if o == nil || IsNil(o.Superuser) {
		var ret bool
		return ret
	}
	return *o.Superuser
}

// GetSuperuserOk returns a tuple with the Superuser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAppExternalAwsRdsConnectionRequest) GetSuperuserOk() (*bool, bool) {
	if o == nil || IsNil(o.Superuser) {
		return nil, false
	}
	return o.Superuser, true
}

// HasSuperuser returns a boolean if a field has been set.
func (o *UpdateAppExternalAwsRdsConnectionRequest) HasSuperuser() bool {
	if o != nil && !IsNil(o.Superuser) {
		return true
	}

	return false
}

// SetSuperuser gets a reference to the given bool and assigns it to the Superuser field.
func (o *UpdateAppExternalAwsRdsConnectionRequest) SetSuperuser(v bool) {
	o.Superuser = &v
}

func (o UpdateAppExternalAwsRdsConnectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAppExternalAwsRdsConnectionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DatabaseName) {
		toSerialize["database_name"] = o.DatabaseName
	}
	if !IsNil(o.DatabaseUser) {
		toSerialize["database_user"] = o.DatabaseUser
	}
	if !IsNil(o.Superuser) {
		toSerialize["superuser"] = o.Superuser
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateAppExternalAwsRdsConnectionRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateAppExternalAwsRdsConnectionRequest := _UpdateAppExternalAwsRdsConnectionRequest{}

	err = json.Unmarshal(data, &varUpdateAppExternalAwsRdsConnectionRequest)

	if err != nil {
		return err
	}

	*o = UpdateAppExternalAwsRdsConnectionRequest(varUpdateAppExternalAwsRdsConnectionRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "database_name")
		delete(additionalProperties, "database_user")
		delete(additionalProperties, "superuser")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateAppExternalAwsRdsConnectionRequest struct {
	value *UpdateAppExternalAwsRdsConnectionRequest
	isSet bool
}

func (v NullableUpdateAppExternalAwsRdsConnectionRequest) Get() *UpdateAppExternalAwsRdsConnectionRequest {
	return v.value
}

func (v *NullableUpdateAppExternalAwsRdsConnectionRequest) Set(val *UpdateAppExternalAwsRdsConnectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAppExternalAwsRdsConnectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAppExternalAwsRdsConnectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAppExternalAwsRdsConnectionRequest(val *UpdateAppExternalAwsRdsConnectionRequest) *NullableUpdateAppExternalAwsRdsConnectionRequest {
	return &NullableUpdateAppExternalAwsRdsConnectionRequest{value: val, isSet: true}
}

func (v NullableUpdateAppExternalAwsRdsConnectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAppExternalAwsRdsConnectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


