/*
Aptible API v1

REST API for the core Aptible platform.

API version: v1
Contact: support@aptible.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the CreateOrUpdateLlmPolicyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrUpdateLlmPolicyRequest{}

// CreateOrUpdateLlmPolicyRequest struct for CreateOrUpdateLlmPolicyRequest
type CreateOrUpdateLlmPolicyRequest struct {
	// List of allowed model identifiers
	Models []string `json:"models,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateOrUpdateLlmPolicyRequest CreateOrUpdateLlmPolicyRequest

// NewCreateOrUpdateLlmPolicyRequest instantiates a new CreateOrUpdateLlmPolicyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrUpdateLlmPolicyRequest() *CreateOrUpdateLlmPolicyRequest {
	this := CreateOrUpdateLlmPolicyRequest{}
	return &this
}

// NewCreateOrUpdateLlmPolicyRequestWithDefaults instantiates a new CreateOrUpdateLlmPolicyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrUpdateLlmPolicyRequestWithDefaults() *CreateOrUpdateLlmPolicyRequest {
	this := CreateOrUpdateLlmPolicyRequest{}
	return &this
}

// GetModels returns the Models field value if set, zero value otherwise.
func (o *CreateOrUpdateLlmPolicyRequest) GetModels() []string {
	if o == nil || IsNil(o.Models) {
		var ret []string
		return ret
	}
	return o.Models
}

// GetModelsOk returns a tuple with the Models field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateLlmPolicyRequest) GetModelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Models) {
		return nil, false
	}
	return o.Models, true
}

// HasModels returns a boolean if a field has been set.
func (o *CreateOrUpdateLlmPolicyRequest) HasModels() bool {
	if o != nil && !IsNil(o.Models) {
		return true
	}

	return false
}

// SetModels gets a reference to the given []string and assigns it to the Models field.
func (o *CreateOrUpdateLlmPolicyRequest) SetModels(v []string) {
	o.Models = v
}

func (o CreateOrUpdateLlmPolicyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrUpdateLlmPolicyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Models) {
		toSerialize["models"] = o.Models
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateOrUpdateLlmPolicyRequest) UnmarshalJSON(data []byte) (err error) {
	varCreateOrUpdateLlmPolicyRequest := _CreateOrUpdateLlmPolicyRequest{}

	err = json.Unmarshal(data, &varCreateOrUpdateLlmPolicyRequest)

	if err != nil {
		return err
	}

	*o = CreateOrUpdateLlmPolicyRequest(varCreateOrUpdateLlmPolicyRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "models")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateOrUpdateLlmPolicyRequest struct {
	value *CreateOrUpdateLlmPolicyRequest
	isSet bool
}

func (v NullableCreateOrUpdateLlmPolicyRequest) Get() *CreateOrUpdateLlmPolicyRequest {
	return v.value
}

func (v *NullableCreateOrUpdateLlmPolicyRequest) Set(val *CreateOrUpdateLlmPolicyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrUpdateLlmPolicyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrUpdateLlmPolicyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrUpdateLlmPolicyRequest(val *CreateOrUpdateLlmPolicyRequest) *NullableCreateOrUpdateLlmPolicyRequest {
	return &NullableCreateOrUpdateLlmPolicyRequest{value: val, isSet: true}
}

func (v NullableCreateOrUpdateLlmPolicyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrUpdateLlmPolicyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


