/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListDeploymentsForSource200ResponseLinksSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDeploymentsForSource200ResponseLinksSource{}

// ListDeploymentsForSource200ResponseLinksSource struct for ListDeploymentsForSource200ResponseLinksSource
type ListDeploymentsForSource200ResponseLinksSource struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListDeploymentsForSource200ResponseLinksSource ListDeploymentsForSource200ResponseLinksSource

// NewListDeploymentsForSource200ResponseLinksSource instantiates a new ListDeploymentsForSource200ResponseLinksSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDeploymentsForSource200ResponseLinksSource() *ListDeploymentsForSource200ResponseLinksSource {
	this := ListDeploymentsForSource200ResponseLinksSource{}
	return &this
}

// NewListDeploymentsForSource200ResponseLinksSourceWithDefaults instantiates a new ListDeploymentsForSource200ResponseLinksSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDeploymentsForSource200ResponseLinksSourceWithDefaults() *ListDeploymentsForSource200ResponseLinksSource {
	this := ListDeploymentsForSource200ResponseLinksSource{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListDeploymentsForSource200ResponseLinksSource) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDeploymentsForSource200ResponseLinksSource) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListDeploymentsForSource200ResponseLinksSource) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListDeploymentsForSource200ResponseLinksSource) SetHref(v string) {
	o.Href = &v
}

func (o ListDeploymentsForSource200ResponseLinksSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDeploymentsForSource200ResponseLinksSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListDeploymentsForSource200ResponseLinksSource) UnmarshalJSON(data []byte) (err error) {
	varListDeploymentsForSource200ResponseLinksSource := _ListDeploymentsForSource200ResponseLinksSource{}

	err = json.Unmarshal(data, &varListDeploymentsForSource200ResponseLinksSource)

	if err != nil {
		return err
	}

	*o = ListDeploymentsForSource200ResponseLinksSource(varListDeploymentsForSource200ResponseLinksSource)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListDeploymentsForSource200ResponseLinksSource struct {
	value *ListDeploymentsForSource200ResponseLinksSource
	isSet bool
}

func (v NullableListDeploymentsForSource200ResponseLinksSource) Get() *ListDeploymentsForSource200ResponseLinksSource {
	return v.value
}

func (v *NullableListDeploymentsForSource200ResponseLinksSource) Set(val *ListDeploymentsForSource200ResponseLinksSource) {
	v.value = val
	v.isSet = true
}

func (v NullableListDeploymentsForSource200ResponseLinksSource) IsSet() bool {
	return v.isSet
}

func (v *NullableListDeploymentsForSource200ResponseLinksSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDeploymentsForSource200ResponseLinksSource(val *ListDeploymentsForSource200ResponseLinksSource) *NullableListDeploymentsForSource200ResponseLinksSource {
	return &NullableListDeploymentsForSource200ResponseLinksSource{value: val, isSet: true}
}

func (v NullableListDeploymentsForSource200ResponseLinksSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDeploymentsForSource200ResponseLinksSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


