/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListPermissions200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPermissions200ResponseLinks{}

// ListPermissions200ResponseLinks struct for ListPermissions200ResponseLinks
type ListPermissions200ResponseLinks struct {
	Account *ListPermissions200ResponseLinksAccount `json:"account,omitempty"`
	Next *ListPermissions200ResponseLinksNext `json:"next,omitempty"`
	Prev *ListPermissions200ResponseLinksPrev `json:"prev,omitempty"`
	Self *ListPermissions200ResponseLinksSelf `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListPermissions200ResponseLinks ListPermissions200ResponseLinks

// NewListPermissions200ResponseLinks instantiates a new ListPermissions200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPermissions200ResponseLinks() *ListPermissions200ResponseLinks {
	this := ListPermissions200ResponseLinks{}
	return &this
}

// NewListPermissions200ResponseLinksWithDefaults instantiates a new ListPermissions200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPermissions200ResponseLinksWithDefaults() *ListPermissions200ResponseLinks {
	this := ListPermissions200ResponseLinks{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *ListPermissions200ResponseLinks) GetAccount() ListPermissions200ResponseLinksAccount {
	if o == nil || IsNil(o.Account) {
		var ret ListPermissions200ResponseLinksAccount
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPermissions200ResponseLinks) GetAccountOk() (*ListPermissions200ResponseLinksAccount, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *ListPermissions200ResponseLinks) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given ListPermissions200ResponseLinksAccount and assigns it to the Account field.
func (o *ListPermissions200ResponseLinks) SetAccount(v ListPermissions200ResponseLinksAccount) {
	o.Account = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *ListPermissions200ResponseLinks) GetNext() ListPermissions200ResponseLinksNext {
	if o == nil || IsNil(o.Next) {
		var ret ListPermissions200ResponseLinksNext
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPermissions200ResponseLinks) GetNextOk() (*ListPermissions200ResponseLinksNext, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *ListPermissions200ResponseLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given ListPermissions200ResponseLinksNext and assigns it to the Next field.
func (o *ListPermissions200ResponseLinks) SetNext(v ListPermissions200ResponseLinksNext) {
	o.Next = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *ListPermissions200ResponseLinks) GetPrev() ListPermissions200ResponseLinksPrev {
	if o == nil || IsNil(o.Prev) {
		var ret ListPermissions200ResponseLinksPrev
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPermissions200ResponseLinks) GetPrevOk() (*ListPermissions200ResponseLinksPrev, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *ListPermissions200ResponseLinks) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given ListPermissions200ResponseLinksPrev and assigns it to the Prev field.
func (o *ListPermissions200ResponseLinks) SetPrev(v ListPermissions200ResponseLinksPrev) {
	o.Prev = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ListPermissions200ResponseLinks) GetSelf() ListPermissions200ResponseLinksSelf {
	if o == nil || IsNil(o.Self) {
		var ret ListPermissions200ResponseLinksSelf
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPermissions200ResponseLinks) GetSelfOk() (*ListPermissions200ResponseLinksSelf, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ListPermissions200ResponseLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ListPermissions200ResponseLinksSelf and assigns it to the Self field.
func (o *ListPermissions200ResponseLinks) SetSelf(v ListPermissions200ResponseLinksSelf) {
	o.Self = &v
}

func (o ListPermissions200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPermissions200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListPermissions200ResponseLinks) UnmarshalJSON(data []byte) (err error) {
	varListPermissions200ResponseLinks := _ListPermissions200ResponseLinks{}

	err = json.Unmarshal(data, &varListPermissions200ResponseLinks)

	if err != nil {
		return err
	}

	*o = ListPermissions200ResponseLinks(varListPermissions200ResponseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account")
		delete(additionalProperties, "next")
		delete(additionalProperties, "prev")
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListPermissions200ResponseLinks struct {
	value *ListPermissions200ResponseLinks
	isSet bool
}

func (v NullableListPermissions200ResponseLinks) Get() *ListPermissions200ResponseLinks {
	return v.value
}

func (v *NullableListPermissions200ResponseLinks) Set(val *ListPermissions200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableListPermissions200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableListPermissions200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPermissions200ResponseLinks(val *ListPermissions200ResponseLinks) *NullableListPermissions200ResponseLinks {
	return &NullableListPermissions200ResponseLinks{value: val, isSet: true}
}

func (v NullableListPermissions200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPermissions200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


