/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListAppsForAccount200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAppsForAccount200ResponseLinks{}

// ListAppsForAccount200ResponseLinks struct for ListAppsForAccount200ResponseLinks
type ListAppsForAccount200ResponseLinks struct {
	Account *ListAppsForAccount200ResponseLinksAccount `json:"account,omitempty"`
	Next *ListAppsForAccount200ResponseLinksNext `json:"next,omitempty"`
	Prev *ListAppsForAccount200ResponseLinksPrev `json:"prev,omitempty"`
	Self *ListAppsForAccount200ResponseLinksSelf `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListAppsForAccount200ResponseLinks ListAppsForAccount200ResponseLinks

// NewListAppsForAccount200ResponseLinks instantiates a new ListAppsForAccount200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAppsForAccount200ResponseLinks() *ListAppsForAccount200ResponseLinks {
	this := ListAppsForAccount200ResponseLinks{}
	return &this
}

// NewListAppsForAccount200ResponseLinksWithDefaults instantiates a new ListAppsForAccount200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAppsForAccount200ResponseLinksWithDefaults() *ListAppsForAccount200ResponseLinks {
	this := ListAppsForAccount200ResponseLinks{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *ListAppsForAccount200ResponseLinks) GetAccount() ListAppsForAccount200ResponseLinksAccount {
	if o == nil || IsNil(o.Account) {
		var ret ListAppsForAccount200ResponseLinksAccount
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAppsForAccount200ResponseLinks) GetAccountOk() (*ListAppsForAccount200ResponseLinksAccount, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *ListAppsForAccount200ResponseLinks) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given ListAppsForAccount200ResponseLinksAccount and assigns it to the Account field.
func (o *ListAppsForAccount200ResponseLinks) SetAccount(v ListAppsForAccount200ResponseLinksAccount) {
	o.Account = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *ListAppsForAccount200ResponseLinks) GetNext() ListAppsForAccount200ResponseLinksNext {
	if o == nil || IsNil(o.Next) {
		var ret ListAppsForAccount200ResponseLinksNext
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAppsForAccount200ResponseLinks) GetNextOk() (*ListAppsForAccount200ResponseLinksNext, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *ListAppsForAccount200ResponseLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given ListAppsForAccount200ResponseLinksNext and assigns it to the Next field.
func (o *ListAppsForAccount200ResponseLinks) SetNext(v ListAppsForAccount200ResponseLinksNext) {
	o.Next = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *ListAppsForAccount200ResponseLinks) GetPrev() ListAppsForAccount200ResponseLinksPrev {
	if o == nil || IsNil(o.Prev) {
		var ret ListAppsForAccount200ResponseLinksPrev
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAppsForAccount200ResponseLinks) GetPrevOk() (*ListAppsForAccount200ResponseLinksPrev, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *ListAppsForAccount200ResponseLinks) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given ListAppsForAccount200ResponseLinksPrev and assigns it to the Prev field.
func (o *ListAppsForAccount200ResponseLinks) SetPrev(v ListAppsForAccount200ResponseLinksPrev) {
	o.Prev = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ListAppsForAccount200ResponseLinks) GetSelf() ListAppsForAccount200ResponseLinksSelf {
	if o == nil || IsNil(o.Self) {
		var ret ListAppsForAccount200ResponseLinksSelf
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAppsForAccount200ResponseLinks) GetSelfOk() (*ListAppsForAccount200ResponseLinksSelf, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ListAppsForAccount200ResponseLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ListAppsForAccount200ResponseLinksSelf and assigns it to the Self field.
func (o *ListAppsForAccount200ResponseLinks) SetSelf(v ListAppsForAccount200ResponseLinksSelf) {
	o.Self = &v
}

func (o ListAppsForAccount200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAppsForAccount200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAppsForAccount200ResponseLinks) UnmarshalJSON(data []byte) (err error) {
	varListAppsForAccount200ResponseLinks := _ListAppsForAccount200ResponseLinks{}

	err = json.Unmarshal(data, &varListAppsForAccount200ResponseLinks)

	if err != nil {
		return err
	}

	*o = ListAppsForAccount200ResponseLinks(varListAppsForAccount200ResponseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account")
		delete(additionalProperties, "next")
		delete(additionalProperties, "prev")
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAppsForAccount200ResponseLinks struct {
	value *ListAppsForAccount200ResponseLinks
	isSet bool
}

func (v NullableListAppsForAccount200ResponseLinks) Get() *ListAppsForAccount200ResponseLinks {
	return v.value
}

func (v *NullableListAppsForAccount200ResponseLinks) Set(val *ListAppsForAccount200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableListAppsForAccount200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableListAppsForAccount200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAppsForAccount200ResponseLinks(val *ListAppsForAccount200ResponseLinks) *NullableListAppsForAccount200ResponseLinks {
	return &NullableListAppsForAccount200ResponseLinks{value: val, isSet: true}
}

func (v NullableListAppsForAccount200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAppsForAccount200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


