/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListOperationsForDatabase200ResponseLinksPrev type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOperationsForDatabase200ResponseLinksPrev{}

// ListOperationsForDatabase200ResponseLinksPrev struct for ListOperationsForDatabase200ResponseLinksPrev
type ListOperationsForDatabase200ResponseLinksPrev struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListOperationsForDatabase200ResponseLinksPrev ListOperationsForDatabase200ResponseLinksPrev

// NewListOperationsForDatabase200ResponseLinksPrev instantiates a new ListOperationsForDatabase200ResponseLinksPrev object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOperationsForDatabase200ResponseLinksPrev() *ListOperationsForDatabase200ResponseLinksPrev {
	this := ListOperationsForDatabase200ResponseLinksPrev{}
	return &this
}

// NewListOperationsForDatabase200ResponseLinksPrevWithDefaults instantiates a new ListOperationsForDatabase200ResponseLinksPrev object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOperationsForDatabase200ResponseLinksPrevWithDefaults() *ListOperationsForDatabase200ResponseLinksPrev {
	this := ListOperationsForDatabase200ResponseLinksPrev{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListOperationsForDatabase200ResponseLinksPrev) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOperationsForDatabase200ResponseLinksPrev) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListOperationsForDatabase200ResponseLinksPrev) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListOperationsForDatabase200ResponseLinksPrev) SetHref(v string) {
	o.Href = &v
}

func (o ListOperationsForDatabase200ResponseLinksPrev) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOperationsForDatabase200ResponseLinksPrev) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListOperationsForDatabase200ResponseLinksPrev) UnmarshalJSON(data []byte) (err error) {
	varListOperationsForDatabase200ResponseLinksPrev := _ListOperationsForDatabase200ResponseLinksPrev{}

	err = json.Unmarshal(data, &varListOperationsForDatabase200ResponseLinksPrev)

	if err != nil {
		return err
	}

	*o = ListOperationsForDatabase200ResponseLinksPrev(varListOperationsForDatabase200ResponseLinksPrev)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListOperationsForDatabase200ResponseLinksPrev struct {
	value *ListOperationsForDatabase200ResponseLinksPrev
	isSet bool
}

func (v NullableListOperationsForDatabase200ResponseLinksPrev) Get() *ListOperationsForDatabase200ResponseLinksPrev {
	return v.value
}

func (v *NullableListOperationsForDatabase200ResponseLinksPrev) Set(val *ListOperationsForDatabase200ResponseLinksPrev) {
	v.value = val
	v.isSet = true
}

func (v NullableListOperationsForDatabase200ResponseLinksPrev) IsSet() bool {
	return v.isSet
}

func (v *NullableListOperationsForDatabase200ResponseLinksPrev) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOperationsForDatabase200ResponseLinksPrev(val *ListOperationsForDatabase200ResponseLinksPrev) *NullableListOperationsForDatabase200ResponseLinksPrev {
	return &NullableListOperationsForDatabase200ResponseLinksPrev{value: val, isSet: true}
}

func (v NullableListOperationsForDatabase200ResponseLinksPrev) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOperationsForDatabase200ResponseLinksPrev) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


