/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListObservationsForApp200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListObservationsForApp200ResponseLinks{}

// ListObservationsForApp200ResponseLinks struct for ListObservationsForApp200ResponseLinks
type ListObservationsForApp200ResponseLinks struct {
	App *ListObservationsForApp200ResponseLinksApp `json:"app,omitempty"`
	Next *ListObservationsForApp200ResponseLinksNext `json:"next,omitempty"`
	Prev *ListObservationsForApp200ResponseLinksPrev `json:"prev,omitempty"`
	Self *ListObservationsForApp200ResponseLinksSelf `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListObservationsForApp200ResponseLinks ListObservationsForApp200ResponseLinks

// NewListObservationsForApp200ResponseLinks instantiates a new ListObservationsForApp200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListObservationsForApp200ResponseLinks() *ListObservationsForApp200ResponseLinks {
	this := ListObservationsForApp200ResponseLinks{}
	return &this
}

// NewListObservationsForApp200ResponseLinksWithDefaults instantiates a new ListObservationsForApp200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListObservationsForApp200ResponseLinksWithDefaults() *ListObservationsForApp200ResponseLinks {
	this := ListObservationsForApp200ResponseLinks{}
	return &this
}

// GetApp returns the App field value if set, zero value otherwise.
func (o *ListObservationsForApp200ResponseLinks) GetApp() ListObservationsForApp200ResponseLinksApp {
	if o == nil || IsNil(o.App) {
		var ret ListObservationsForApp200ResponseLinksApp
		return ret
	}
	return *o.App
}

// GetAppOk returns a tuple with the App field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListObservationsForApp200ResponseLinks) GetAppOk() (*ListObservationsForApp200ResponseLinksApp, bool) {
	if o == nil || IsNil(o.App) {
		return nil, false
	}
	return o.App, true
}

// HasApp returns a boolean if a field has been set.
func (o *ListObservationsForApp200ResponseLinks) HasApp() bool {
	if o != nil && !IsNil(o.App) {
		return true
	}

	return false
}

// SetApp gets a reference to the given ListObservationsForApp200ResponseLinksApp and assigns it to the App field.
func (o *ListObservationsForApp200ResponseLinks) SetApp(v ListObservationsForApp200ResponseLinksApp) {
	o.App = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *ListObservationsForApp200ResponseLinks) GetNext() ListObservationsForApp200ResponseLinksNext {
	if o == nil || IsNil(o.Next) {
		var ret ListObservationsForApp200ResponseLinksNext
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListObservationsForApp200ResponseLinks) GetNextOk() (*ListObservationsForApp200ResponseLinksNext, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *ListObservationsForApp200ResponseLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given ListObservationsForApp200ResponseLinksNext and assigns it to the Next field.
func (o *ListObservationsForApp200ResponseLinks) SetNext(v ListObservationsForApp200ResponseLinksNext) {
	o.Next = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *ListObservationsForApp200ResponseLinks) GetPrev() ListObservationsForApp200ResponseLinksPrev {
	if o == nil || IsNil(o.Prev) {
		var ret ListObservationsForApp200ResponseLinksPrev
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListObservationsForApp200ResponseLinks) GetPrevOk() (*ListObservationsForApp200ResponseLinksPrev, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *ListObservationsForApp200ResponseLinks) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given ListObservationsForApp200ResponseLinksPrev and assigns it to the Prev field.
func (o *ListObservationsForApp200ResponseLinks) SetPrev(v ListObservationsForApp200ResponseLinksPrev) {
	o.Prev = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ListObservationsForApp200ResponseLinks) GetSelf() ListObservationsForApp200ResponseLinksSelf {
	if o == nil || IsNil(o.Self) {
		var ret ListObservationsForApp200ResponseLinksSelf
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListObservationsForApp200ResponseLinks) GetSelfOk() (*ListObservationsForApp200ResponseLinksSelf, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ListObservationsForApp200ResponseLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ListObservationsForApp200ResponseLinksSelf and assigns it to the Self field.
func (o *ListObservationsForApp200ResponseLinks) SetSelf(v ListObservationsForApp200ResponseLinksSelf) {
	o.Self = &v
}

func (o ListObservationsForApp200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListObservationsForApp200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.App) {
		toSerialize["app"] = o.App
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListObservationsForApp200ResponseLinks) UnmarshalJSON(data []byte) (err error) {
	varListObservationsForApp200ResponseLinks := _ListObservationsForApp200ResponseLinks{}

	err = json.Unmarshal(data, &varListObservationsForApp200ResponseLinks)

	if err != nil {
		return err
	}

	*o = ListObservationsForApp200ResponseLinks(varListObservationsForApp200ResponseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "app")
		delete(additionalProperties, "next")
		delete(additionalProperties, "prev")
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListObservationsForApp200ResponseLinks struct {
	value *ListObservationsForApp200ResponseLinks
	isSet bool
}

func (v NullableListObservationsForApp200ResponseLinks) Get() *ListObservationsForApp200ResponseLinks {
	return v.value
}

func (v *NullableListObservationsForApp200ResponseLinks) Set(val *ListObservationsForApp200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableListObservationsForApp200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableListObservationsForApp200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListObservationsForApp200ResponseLinks(val *ListObservationsForApp200ResponseLinks) *NullableListObservationsForApp200ResponseLinks {
	return &NullableListObservationsForApp200ResponseLinks{value: val, isSet: true}
}

func (v NullableListObservationsForApp200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListObservationsForApp200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


