/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListIntrustionDetectionReportsForStack200ResponseLinksNext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListIntrustionDetectionReportsForStack200ResponseLinksNext{}

// ListIntrustionDetectionReportsForStack200ResponseLinksNext struct for ListIntrustionDetectionReportsForStack200ResponseLinksNext
type ListIntrustionDetectionReportsForStack200ResponseLinksNext struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListIntrustionDetectionReportsForStack200ResponseLinksNext ListIntrustionDetectionReportsForStack200ResponseLinksNext

// NewListIntrustionDetectionReportsForStack200ResponseLinksNext instantiates a new ListIntrustionDetectionReportsForStack200ResponseLinksNext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListIntrustionDetectionReportsForStack200ResponseLinksNext() *ListIntrustionDetectionReportsForStack200ResponseLinksNext {
	this := ListIntrustionDetectionReportsForStack200ResponseLinksNext{}
	return &this
}

// NewListIntrustionDetectionReportsForStack200ResponseLinksNextWithDefaults instantiates a new ListIntrustionDetectionReportsForStack200ResponseLinksNext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListIntrustionDetectionReportsForStack200ResponseLinksNextWithDefaults() *ListIntrustionDetectionReportsForStack200ResponseLinksNext {
	this := ListIntrustionDetectionReportsForStack200ResponseLinksNext{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListIntrustionDetectionReportsForStack200ResponseLinksNext) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListIntrustionDetectionReportsForStack200ResponseLinksNext) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListIntrustionDetectionReportsForStack200ResponseLinksNext) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListIntrustionDetectionReportsForStack200ResponseLinksNext) SetHref(v string) {
	o.Href = &v
}

func (o ListIntrustionDetectionReportsForStack200ResponseLinksNext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListIntrustionDetectionReportsForStack200ResponseLinksNext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListIntrustionDetectionReportsForStack200ResponseLinksNext) UnmarshalJSON(data []byte) (err error) {
	varListIntrustionDetectionReportsForStack200ResponseLinksNext := _ListIntrustionDetectionReportsForStack200ResponseLinksNext{}

	err = json.Unmarshal(data, &varListIntrustionDetectionReportsForStack200ResponseLinksNext)

	if err != nil {
		return err
	}

	*o = ListIntrustionDetectionReportsForStack200ResponseLinksNext(varListIntrustionDetectionReportsForStack200ResponseLinksNext)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListIntrustionDetectionReportsForStack200ResponseLinksNext struct {
	value *ListIntrustionDetectionReportsForStack200ResponseLinksNext
	isSet bool
}

func (v NullableListIntrustionDetectionReportsForStack200ResponseLinksNext) Get() *ListIntrustionDetectionReportsForStack200ResponseLinksNext {
	return v.value
}

func (v *NullableListIntrustionDetectionReportsForStack200ResponseLinksNext) Set(val *ListIntrustionDetectionReportsForStack200ResponseLinksNext) {
	v.value = val
	v.isSet = true
}

func (v NullableListIntrustionDetectionReportsForStack200ResponseLinksNext) IsSet() bool {
	return v.isSet
}

func (v *NullableListIntrustionDetectionReportsForStack200ResponseLinksNext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListIntrustionDetectionReportsForStack200ResponseLinksNext(val *ListIntrustionDetectionReportsForStack200ResponseLinksNext) *NullableListIntrustionDetectionReportsForStack200ResponseLinksNext {
	return &NullableListIntrustionDetectionReportsForStack200ResponseLinksNext{value: val, isSet: true}
}

func (v NullableListIntrustionDetectionReportsForStack200ResponseLinksNext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListIntrustionDetectionReportsForStack200ResponseLinksNext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


