/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListWidgetsForDashboard200ResponseLinksSelf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListWidgetsForDashboard200ResponseLinksSelf{}

// ListWidgetsForDashboard200ResponseLinksSelf struct for ListWidgetsForDashboard200ResponseLinksSelf
type ListWidgetsForDashboard200ResponseLinksSelf struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListWidgetsForDashboard200ResponseLinksSelf ListWidgetsForDashboard200ResponseLinksSelf

// NewListWidgetsForDashboard200ResponseLinksSelf instantiates a new ListWidgetsForDashboard200ResponseLinksSelf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListWidgetsForDashboard200ResponseLinksSelf() *ListWidgetsForDashboard200ResponseLinksSelf {
	this := ListWidgetsForDashboard200ResponseLinksSelf{}
	return &this
}

// NewListWidgetsForDashboard200ResponseLinksSelfWithDefaults instantiates a new ListWidgetsForDashboard200ResponseLinksSelf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListWidgetsForDashboard200ResponseLinksSelfWithDefaults() *ListWidgetsForDashboard200ResponseLinksSelf {
	this := ListWidgetsForDashboard200ResponseLinksSelf{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListWidgetsForDashboard200ResponseLinksSelf) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetsForDashboard200ResponseLinksSelf) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListWidgetsForDashboard200ResponseLinksSelf) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListWidgetsForDashboard200ResponseLinksSelf) SetHref(v string) {
	o.Href = &v
}

func (o ListWidgetsForDashboard200ResponseLinksSelf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListWidgetsForDashboard200ResponseLinksSelf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListWidgetsForDashboard200ResponseLinksSelf) UnmarshalJSON(data []byte) (err error) {
	varListWidgetsForDashboard200ResponseLinksSelf := _ListWidgetsForDashboard200ResponseLinksSelf{}

	err = json.Unmarshal(data, &varListWidgetsForDashboard200ResponseLinksSelf)

	if err != nil {
		return err
	}

	*o = ListWidgetsForDashboard200ResponseLinksSelf(varListWidgetsForDashboard200ResponseLinksSelf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListWidgetsForDashboard200ResponseLinksSelf struct {
	value *ListWidgetsForDashboard200ResponseLinksSelf
	isSet bool
}

func (v NullableListWidgetsForDashboard200ResponseLinksSelf) Get() *ListWidgetsForDashboard200ResponseLinksSelf {
	return v.value
}

func (v *NullableListWidgetsForDashboard200ResponseLinksSelf) Set(val *ListWidgetsForDashboard200ResponseLinksSelf) {
	v.value = val
	v.isSet = true
}

func (v NullableListWidgetsForDashboard200ResponseLinksSelf) IsSet() bool {
	return v.isSet
}

func (v *NullableListWidgetsForDashboard200ResponseLinksSelf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListWidgetsForDashboard200ResponseLinksSelf(val *ListWidgetsForDashboard200ResponseLinksSelf) *NullableListWidgetsForDashboard200ResponseLinksSelf {
	return &NullableListWidgetsForDashboard200ResponseLinksSelf{value: val, isSet: true}
}

func (v NullableListWidgetsForDashboard200ResponseLinksSelf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListWidgetsForDashboard200ResponseLinksSelf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


