/*
Aptible API v1

REST API for the core Aptible platform.

API version: v1
Contact: support@aptible.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListLlmPoliciesForAccount200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListLlmPoliciesForAccount200Response{}

// ListLlmPoliciesForAccount200Response struct for ListLlmPoliciesForAccount200Response
type ListLlmPoliciesForAccount200Response struct {
	Embedded *ListLlmPoliciesForAccount200ResponseEmbedded `json:"_embedded,omitempty"`
	Links map[string]interface{} `json:"_links,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListLlmPoliciesForAccount200Response ListLlmPoliciesForAccount200Response

// NewListLlmPoliciesForAccount200Response instantiates a new ListLlmPoliciesForAccount200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListLlmPoliciesForAccount200Response() *ListLlmPoliciesForAccount200Response {
	this := ListLlmPoliciesForAccount200Response{}
	return &this
}

// NewListLlmPoliciesForAccount200ResponseWithDefaults instantiates a new ListLlmPoliciesForAccount200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListLlmPoliciesForAccount200ResponseWithDefaults() *ListLlmPoliciesForAccount200Response {
	this := ListLlmPoliciesForAccount200Response{}
	return &this
}

// GetEmbedded returns the Embedded field value if set, zero value otherwise.
func (o *ListLlmPoliciesForAccount200Response) GetEmbedded() ListLlmPoliciesForAccount200ResponseEmbedded {
	if o == nil || IsNil(o.Embedded) {
		var ret ListLlmPoliciesForAccount200ResponseEmbedded
		return ret
	}
	return *o.Embedded
}

// GetEmbeddedOk returns a tuple with the Embedded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLlmPoliciesForAccount200Response) GetEmbeddedOk() (*ListLlmPoliciesForAccount200ResponseEmbedded, bool) {
	if o == nil || IsNil(o.Embedded) {
		return nil, false
	}
	return o.Embedded, true
}

// HasEmbedded returns a boolean if a field has been set.
func (o *ListLlmPoliciesForAccount200Response) HasEmbedded() bool {
	if o != nil && !IsNil(o.Embedded) {
		return true
	}

	return false
}

// SetEmbedded gets a reference to the given ListLlmPoliciesForAccount200ResponseEmbedded and assigns it to the Embedded field.
func (o *ListLlmPoliciesForAccount200Response) SetEmbedded(v ListLlmPoliciesForAccount200ResponseEmbedded) {
	o.Embedded = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *ListLlmPoliciesForAccount200Response) GetLinks() map[string]interface{} {
	if o == nil || IsNil(o.Links) {
		var ret map[string]interface{}
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLlmPoliciesForAccount200Response) GetLinksOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Links) {
		return map[string]interface{}{}, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *ListLlmPoliciesForAccount200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]interface{} and assigns it to the Links field.
func (o *ListLlmPoliciesForAccount200Response) SetLinks(v map[string]interface{}) {
	o.Links = v
}

func (o ListLlmPoliciesForAccount200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListLlmPoliciesForAccount200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Embedded) {
		toSerialize["_embedded"] = o.Embedded
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListLlmPoliciesForAccount200Response) UnmarshalJSON(data []byte) (err error) {
	varListLlmPoliciesForAccount200Response := _ListLlmPoliciesForAccount200Response{}

	err = json.Unmarshal(data, &varListLlmPoliciesForAccount200Response)

	if err != nil {
		return err
	}

	*o = ListLlmPoliciesForAccount200Response(varListLlmPoliciesForAccount200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "_embedded")
		delete(additionalProperties, "_links")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListLlmPoliciesForAccount200Response struct {
	value *ListLlmPoliciesForAccount200Response
	isSet bool
}

func (v NullableListLlmPoliciesForAccount200Response) Get() *ListLlmPoliciesForAccount200Response {
	return v.value
}

func (v *NullableListLlmPoliciesForAccount200Response) Set(val *ListLlmPoliciesForAccount200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListLlmPoliciesForAccount200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListLlmPoliciesForAccount200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListLlmPoliciesForAccount200Response(val *ListLlmPoliciesForAccount200Response) *NullableListLlmPoliciesForAccount200Response {
	return &NullableListLlmPoliciesForAccount200Response{value: val, isSet: true}
}

func (v NullableListLlmPoliciesForAccount200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListLlmPoliciesForAccount200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


