/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListOperationsForImage200ResponseEmbedded type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOperationsForImage200ResponseEmbedded{}

// ListOperationsForImage200ResponseEmbedded struct for ListOperationsForImage200ResponseEmbedded
type ListOperationsForImage200ResponseEmbedded struct {
	Operations []Operation `json:"operations,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListOperationsForImage200ResponseEmbedded ListOperationsForImage200ResponseEmbedded

// NewListOperationsForImage200ResponseEmbedded instantiates a new ListOperationsForImage200ResponseEmbedded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOperationsForImage200ResponseEmbedded() *ListOperationsForImage200ResponseEmbedded {
	this := ListOperationsForImage200ResponseEmbedded{}
	return &this
}

// NewListOperationsForImage200ResponseEmbeddedWithDefaults instantiates a new ListOperationsForImage200ResponseEmbedded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOperationsForImage200ResponseEmbeddedWithDefaults() *ListOperationsForImage200ResponseEmbedded {
	this := ListOperationsForImage200ResponseEmbedded{}
	return &this
}

// GetOperations returns the Operations field value if set, zero value otherwise.
func (o *ListOperationsForImage200ResponseEmbedded) GetOperations() []Operation {
	if o == nil || IsNil(o.Operations) {
		var ret []Operation
		return ret
	}
	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOperationsForImage200ResponseEmbedded) GetOperationsOk() ([]Operation, bool) {
	if o == nil || IsNil(o.Operations) {
		return nil, false
	}
	return o.Operations, true
}

// HasOperations returns a boolean if a field has been set.
func (o *ListOperationsForImage200ResponseEmbedded) HasOperations() bool {
	if o != nil && !IsNil(o.Operations) {
		return true
	}

	return false
}

// SetOperations gets a reference to the given []Operation and assigns it to the Operations field.
func (o *ListOperationsForImage200ResponseEmbedded) SetOperations(v []Operation) {
	o.Operations = v
}

func (o ListOperationsForImage200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOperationsForImage200ResponseEmbedded) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Operations) {
		toSerialize["operations"] = o.Operations
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListOperationsForImage200ResponseEmbedded) UnmarshalJSON(data []byte) (err error) {
	varListOperationsForImage200ResponseEmbedded := _ListOperationsForImage200ResponseEmbedded{}

	err = json.Unmarshal(data, &varListOperationsForImage200ResponseEmbedded)

	if err != nil {
		return err
	}

	*o = ListOperationsForImage200ResponseEmbedded(varListOperationsForImage200ResponseEmbedded)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "operations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListOperationsForImage200ResponseEmbedded struct {
	value *ListOperationsForImage200ResponseEmbedded
	isSet bool
}

func (v NullableListOperationsForImage200ResponseEmbedded) Get() *ListOperationsForImage200ResponseEmbedded {
	return v.value
}

func (v *NullableListOperationsForImage200ResponseEmbedded) Set(val *ListOperationsForImage200ResponseEmbedded) {
	v.value = val
	v.isSet = true
}

func (v NullableListOperationsForImage200ResponseEmbedded) IsSet() bool {
	return v.isSet
}

func (v *NullableListOperationsForImage200ResponseEmbedded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOperationsForImage200ResponseEmbedded(val *ListOperationsForImage200ResponseEmbedded) *NullableListOperationsForImage200ResponseEmbedded {
	return &NullableListOperationsForImage200ResponseEmbedded{value: val, isSet: true}
}

func (v NullableListOperationsForImage200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOperationsForImage200ResponseEmbedded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


