/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListOperationsForDatabaseCredential200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOperationsForDatabaseCredential200ResponseLinks{}

// ListOperationsForDatabaseCredential200ResponseLinks struct for ListOperationsForDatabaseCredential200ResponseLinks
type ListOperationsForDatabaseCredential200ResponseLinks struct {
	Next *ListOperationsForDatabaseCredential200ResponseLinksNext `json:"next,omitempty"`
	Prev *ListOperationsForDatabaseCredential200ResponseLinksPrev `json:"prev,omitempty"`
	Self *ListOperationsForDatabaseCredential200ResponseLinksSelf `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListOperationsForDatabaseCredential200ResponseLinks ListOperationsForDatabaseCredential200ResponseLinks

// NewListOperationsForDatabaseCredential200ResponseLinks instantiates a new ListOperationsForDatabaseCredential200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOperationsForDatabaseCredential200ResponseLinks() *ListOperationsForDatabaseCredential200ResponseLinks {
	this := ListOperationsForDatabaseCredential200ResponseLinks{}
	return &this
}

// NewListOperationsForDatabaseCredential200ResponseLinksWithDefaults instantiates a new ListOperationsForDatabaseCredential200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOperationsForDatabaseCredential200ResponseLinksWithDefaults() *ListOperationsForDatabaseCredential200ResponseLinks {
	this := ListOperationsForDatabaseCredential200ResponseLinks{}
	return &this
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *ListOperationsForDatabaseCredential200ResponseLinks) GetNext() ListOperationsForDatabaseCredential200ResponseLinksNext {
	if o == nil || IsNil(o.Next) {
		var ret ListOperationsForDatabaseCredential200ResponseLinksNext
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOperationsForDatabaseCredential200ResponseLinks) GetNextOk() (*ListOperationsForDatabaseCredential200ResponseLinksNext, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *ListOperationsForDatabaseCredential200ResponseLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given ListOperationsForDatabaseCredential200ResponseLinksNext and assigns it to the Next field.
func (o *ListOperationsForDatabaseCredential200ResponseLinks) SetNext(v ListOperationsForDatabaseCredential200ResponseLinksNext) {
	o.Next = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *ListOperationsForDatabaseCredential200ResponseLinks) GetPrev() ListOperationsForDatabaseCredential200ResponseLinksPrev {
	if o == nil || IsNil(o.Prev) {
		var ret ListOperationsForDatabaseCredential200ResponseLinksPrev
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOperationsForDatabaseCredential200ResponseLinks) GetPrevOk() (*ListOperationsForDatabaseCredential200ResponseLinksPrev, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *ListOperationsForDatabaseCredential200ResponseLinks) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given ListOperationsForDatabaseCredential200ResponseLinksPrev and assigns it to the Prev field.
func (o *ListOperationsForDatabaseCredential200ResponseLinks) SetPrev(v ListOperationsForDatabaseCredential200ResponseLinksPrev) {
	o.Prev = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ListOperationsForDatabaseCredential200ResponseLinks) GetSelf() ListOperationsForDatabaseCredential200ResponseLinksSelf {
	if o == nil || IsNil(o.Self) {
		var ret ListOperationsForDatabaseCredential200ResponseLinksSelf
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOperationsForDatabaseCredential200ResponseLinks) GetSelfOk() (*ListOperationsForDatabaseCredential200ResponseLinksSelf, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ListOperationsForDatabaseCredential200ResponseLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ListOperationsForDatabaseCredential200ResponseLinksSelf and assigns it to the Self field.
func (o *ListOperationsForDatabaseCredential200ResponseLinks) SetSelf(v ListOperationsForDatabaseCredential200ResponseLinksSelf) {
	o.Self = &v
}

func (o ListOperationsForDatabaseCredential200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOperationsForDatabaseCredential200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListOperationsForDatabaseCredential200ResponseLinks) UnmarshalJSON(data []byte) (err error) {
	varListOperationsForDatabaseCredential200ResponseLinks := _ListOperationsForDatabaseCredential200ResponseLinks{}

	err = json.Unmarshal(data, &varListOperationsForDatabaseCredential200ResponseLinks)

	if err != nil {
		return err
	}

	*o = ListOperationsForDatabaseCredential200ResponseLinks(varListOperationsForDatabaseCredential200ResponseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "next")
		delete(additionalProperties, "prev")
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListOperationsForDatabaseCredential200ResponseLinks struct {
	value *ListOperationsForDatabaseCredential200ResponseLinks
	isSet bool
}

func (v NullableListOperationsForDatabaseCredential200ResponseLinks) Get() *ListOperationsForDatabaseCredential200ResponseLinks {
	return v.value
}

func (v *NullableListOperationsForDatabaseCredential200ResponseLinks) Set(val *ListOperationsForDatabaseCredential200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableListOperationsForDatabaseCredential200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableListOperationsForDatabaseCredential200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOperationsForDatabaseCredential200ResponseLinks(val *ListOperationsForDatabaseCredential200ResponseLinks) *NullableListOperationsForDatabaseCredential200ResponseLinks {
	return &NullableListOperationsForDatabaseCredential200ResponseLinks{value: val, isSet: true}
}

func (v NullableListOperationsForDatabaseCredential200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOperationsForDatabaseCredential200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


