/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the PermissionLinksAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionLinksAccount{}

// PermissionLinksAccount struct for PermissionLinksAccount
type PermissionLinksAccount struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PermissionLinksAccount PermissionLinksAccount

// NewPermissionLinksAccount instantiates a new PermissionLinksAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionLinksAccount() *PermissionLinksAccount {
	this := PermissionLinksAccount{}
	return &this
}

// NewPermissionLinksAccountWithDefaults instantiates a new PermissionLinksAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionLinksAccountWithDefaults() *PermissionLinksAccount {
	this := PermissionLinksAccount{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *PermissionLinksAccount) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionLinksAccount) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *PermissionLinksAccount) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *PermissionLinksAccount) SetHref(v string) {
	o.Href = &v
}

func (o PermissionLinksAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionLinksAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PermissionLinksAccount) UnmarshalJSON(data []byte) (err error) {
	varPermissionLinksAccount := _PermissionLinksAccount{}

	err = json.Unmarshal(data, &varPermissionLinksAccount)

	if err != nil {
		return err
	}

	*o = PermissionLinksAccount(varPermissionLinksAccount)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePermissionLinksAccount struct {
	value *PermissionLinksAccount
	isSet bool
}

func (v NullablePermissionLinksAccount) Get() *PermissionLinksAccount {
	return v.value
}

func (v *NullablePermissionLinksAccount) Set(val *PermissionLinksAccount) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionLinksAccount) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionLinksAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionLinksAccount(val *PermissionLinksAccount) *NullablePermissionLinksAccount {
	return &NullablePermissionLinksAccount{value: val, isSet: true}
}

func (v NullablePermissionLinksAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionLinksAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


