/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListEphemeralContainersForLogDrain200ResponseLinksNext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListEphemeralContainersForLogDrain200ResponseLinksNext{}

// ListEphemeralContainersForLogDrain200ResponseLinksNext struct for ListEphemeralContainersForLogDrain200ResponseLinksNext
type ListEphemeralContainersForLogDrain200ResponseLinksNext struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListEphemeralContainersForLogDrain200ResponseLinksNext ListEphemeralContainersForLogDrain200ResponseLinksNext

// NewListEphemeralContainersForLogDrain200ResponseLinksNext instantiates a new ListEphemeralContainersForLogDrain200ResponseLinksNext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListEphemeralContainersForLogDrain200ResponseLinksNext() *ListEphemeralContainersForLogDrain200ResponseLinksNext {
	this := ListEphemeralContainersForLogDrain200ResponseLinksNext{}
	return &this
}

// NewListEphemeralContainersForLogDrain200ResponseLinksNextWithDefaults instantiates a new ListEphemeralContainersForLogDrain200ResponseLinksNext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListEphemeralContainersForLogDrain200ResponseLinksNextWithDefaults() *ListEphemeralContainersForLogDrain200ResponseLinksNext {
	this := ListEphemeralContainersForLogDrain200ResponseLinksNext{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListEphemeralContainersForLogDrain200ResponseLinksNext) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListEphemeralContainersForLogDrain200ResponseLinksNext) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListEphemeralContainersForLogDrain200ResponseLinksNext) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListEphemeralContainersForLogDrain200ResponseLinksNext) SetHref(v string) {
	o.Href = &v
}

func (o ListEphemeralContainersForLogDrain200ResponseLinksNext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListEphemeralContainersForLogDrain200ResponseLinksNext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListEphemeralContainersForLogDrain200ResponseLinksNext) UnmarshalJSON(data []byte) (err error) {
	varListEphemeralContainersForLogDrain200ResponseLinksNext := _ListEphemeralContainersForLogDrain200ResponseLinksNext{}

	err = json.Unmarshal(data, &varListEphemeralContainersForLogDrain200ResponseLinksNext)

	if err != nil {
		return err
	}

	*o = ListEphemeralContainersForLogDrain200ResponseLinksNext(varListEphemeralContainersForLogDrain200ResponseLinksNext)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListEphemeralContainersForLogDrain200ResponseLinksNext struct {
	value *ListEphemeralContainersForLogDrain200ResponseLinksNext
	isSet bool
}

func (v NullableListEphemeralContainersForLogDrain200ResponseLinksNext) Get() *ListEphemeralContainersForLogDrain200ResponseLinksNext {
	return v.value
}

func (v *NullableListEphemeralContainersForLogDrain200ResponseLinksNext) Set(val *ListEphemeralContainersForLogDrain200ResponseLinksNext) {
	v.value = val
	v.isSet = true
}

func (v NullableListEphemeralContainersForLogDrain200ResponseLinksNext) IsSet() bool {
	return v.isSet
}

func (v *NullableListEphemeralContainersForLogDrain200ResponseLinksNext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListEphemeralContainersForLogDrain200ResponseLinksNext(val *ListEphemeralContainersForLogDrain200ResponseLinksNext) *NullableListEphemeralContainersForLogDrain200ResponseLinksNext {
	return &NullableListEphemeralContainersForLogDrain200ResponseLinksNext{value: val, isSet: true}
}

func (v NullableListEphemeralContainersForLogDrain200ResponseLinksNext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListEphemeralContainersForLogDrain200ResponseLinksNext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


