/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListBackups200ResponseLinksPrev type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListBackups200ResponseLinksPrev{}

// ListBackups200ResponseLinksPrev struct for ListBackups200ResponseLinksPrev
type ListBackups200ResponseLinksPrev struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListBackups200ResponseLinksPrev ListBackups200ResponseLinksPrev

// NewListBackups200ResponseLinksPrev instantiates a new ListBackups200ResponseLinksPrev object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListBackups200ResponseLinksPrev() *ListBackups200ResponseLinksPrev {
	this := ListBackups200ResponseLinksPrev{}
	return &this
}

// NewListBackups200ResponseLinksPrevWithDefaults instantiates a new ListBackups200ResponseLinksPrev object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListBackups200ResponseLinksPrevWithDefaults() *ListBackups200ResponseLinksPrev {
	this := ListBackups200ResponseLinksPrev{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListBackups200ResponseLinksPrev) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackups200ResponseLinksPrev) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListBackups200ResponseLinksPrev) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListBackups200ResponseLinksPrev) SetHref(v string) {
	o.Href = &v
}

func (o ListBackups200ResponseLinksPrev) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListBackups200ResponseLinksPrev) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListBackups200ResponseLinksPrev) UnmarshalJSON(data []byte) (err error) {
	varListBackups200ResponseLinksPrev := _ListBackups200ResponseLinksPrev{}

	err = json.Unmarshal(data, &varListBackups200ResponseLinksPrev)

	if err != nil {
		return err
	}

	*o = ListBackups200ResponseLinksPrev(varListBackups200ResponseLinksPrev)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListBackups200ResponseLinksPrev struct {
	value *ListBackups200ResponseLinksPrev
	isSet bool
}

func (v NullableListBackups200ResponseLinksPrev) Get() *ListBackups200ResponseLinksPrev {
	return v.value
}

func (v *NullableListBackups200ResponseLinksPrev) Set(val *ListBackups200ResponseLinksPrev) {
	v.value = val
	v.isSet = true
}

func (v NullableListBackups200ResponseLinksPrev) IsSet() bool {
	return v.isSet
}

func (v *NullableListBackups200ResponseLinksPrev) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBackups200ResponseLinksPrev(val *ListBackups200ResponseLinksPrev) *NullableListBackups200ResponseLinksPrev {
	return &NullableListBackups200ResponseLinksPrev{value: val, isSet: true}
}

func (v NullableListBackups200ResponseLinksPrev) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBackups200ResponseLinksPrev) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


