/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListVpnTunnelsForStack200ResponseLinksSelf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListVpnTunnelsForStack200ResponseLinksSelf{}

// ListVpnTunnelsForStack200ResponseLinksSelf struct for ListVpnTunnelsForStack200ResponseLinksSelf
type ListVpnTunnelsForStack200ResponseLinksSelf struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListVpnTunnelsForStack200ResponseLinksSelf ListVpnTunnelsForStack200ResponseLinksSelf

// NewListVpnTunnelsForStack200ResponseLinksSelf instantiates a new ListVpnTunnelsForStack200ResponseLinksSelf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListVpnTunnelsForStack200ResponseLinksSelf() *ListVpnTunnelsForStack200ResponseLinksSelf {
	this := ListVpnTunnelsForStack200ResponseLinksSelf{}
	return &this
}

// NewListVpnTunnelsForStack200ResponseLinksSelfWithDefaults instantiates a new ListVpnTunnelsForStack200ResponseLinksSelf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListVpnTunnelsForStack200ResponseLinksSelfWithDefaults() *ListVpnTunnelsForStack200ResponseLinksSelf {
	this := ListVpnTunnelsForStack200ResponseLinksSelf{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListVpnTunnelsForStack200ResponseLinksSelf) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVpnTunnelsForStack200ResponseLinksSelf) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListVpnTunnelsForStack200ResponseLinksSelf) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListVpnTunnelsForStack200ResponseLinksSelf) SetHref(v string) {
	o.Href = &v
}

func (o ListVpnTunnelsForStack200ResponseLinksSelf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListVpnTunnelsForStack200ResponseLinksSelf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListVpnTunnelsForStack200ResponseLinksSelf) UnmarshalJSON(data []byte) (err error) {
	varListVpnTunnelsForStack200ResponseLinksSelf := _ListVpnTunnelsForStack200ResponseLinksSelf{}

	err = json.Unmarshal(data, &varListVpnTunnelsForStack200ResponseLinksSelf)

	if err != nil {
		return err
	}

	*o = ListVpnTunnelsForStack200ResponseLinksSelf(varListVpnTunnelsForStack200ResponseLinksSelf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListVpnTunnelsForStack200ResponseLinksSelf struct {
	value *ListVpnTunnelsForStack200ResponseLinksSelf
	isSet bool
}

func (v NullableListVpnTunnelsForStack200ResponseLinksSelf) Get() *ListVpnTunnelsForStack200ResponseLinksSelf {
	return v.value
}

func (v *NullableListVpnTunnelsForStack200ResponseLinksSelf) Set(val *ListVpnTunnelsForStack200ResponseLinksSelf) {
	v.value = val
	v.isSet = true
}

func (v NullableListVpnTunnelsForStack200ResponseLinksSelf) IsSet() bool {
	return v.isSet
}

func (v *NullableListVpnTunnelsForStack200ResponseLinksSelf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListVpnTunnelsForStack200ResponseLinksSelf(val *ListVpnTunnelsForStack200ResponseLinksSelf) *NullableListVpnTunnelsForStack200ResponseLinksSelf {
	return &NullableListVpnTunnelsForStack200ResponseLinksSelf{value: val, isSet: true}
}

func (v NullableListVpnTunnelsForStack200ResponseLinksSelf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListVpnTunnelsForStack200ResponseLinksSelf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


