/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListVpcPeersForStack200ResponseLinksSelf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListVpcPeersForStack200ResponseLinksSelf{}

// ListVpcPeersForStack200ResponseLinksSelf struct for ListVpcPeersForStack200ResponseLinksSelf
type ListVpcPeersForStack200ResponseLinksSelf struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListVpcPeersForStack200ResponseLinksSelf ListVpcPeersForStack200ResponseLinksSelf

// NewListVpcPeersForStack200ResponseLinksSelf instantiates a new ListVpcPeersForStack200ResponseLinksSelf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListVpcPeersForStack200ResponseLinksSelf() *ListVpcPeersForStack200ResponseLinksSelf {
	this := ListVpcPeersForStack200ResponseLinksSelf{}
	return &this
}

// NewListVpcPeersForStack200ResponseLinksSelfWithDefaults instantiates a new ListVpcPeersForStack200ResponseLinksSelf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListVpcPeersForStack200ResponseLinksSelfWithDefaults() *ListVpcPeersForStack200ResponseLinksSelf {
	this := ListVpcPeersForStack200ResponseLinksSelf{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListVpcPeersForStack200ResponseLinksSelf) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVpcPeersForStack200ResponseLinksSelf) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListVpcPeersForStack200ResponseLinksSelf) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListVpcPeersForStack200ResponseLinksSelf) SetHref(v string) {
	o.Href = &v
}

func (o ListVpcPeersForStack200ResponseLinksSelf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListVpcPeersForStack200ResponseLinksSelf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListVpcPeersForStack200ResponseLinksSelf) UnmarshalJSON(data []byte) (err error) {
	varListVpcPeersForStack200ResponseLinksSelf := _ListVpcPeersForStack200ResponseLinksSelf{}

	err = json.Unmarshal(data, &varListVpcPeersForStack200ResponseLinksSelf)

	if err != nil {
		return err
	}

	*o = ListVpcPeersForStack200ResponseLinksSelf(varListVpcPeersForStack200ResponseLinksSelf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListVpcPeersForStack200ResponseLinksSelf struct {
	value *ListVpcPeersForStack200ResponseLinksSelf
	isSet bool
}

func (v NullableListVpcPeersForStack200ResponseLinksSelf) Get() *ListVpcPeersForStack200ResponseLinksSelf {
	return v.value
}

func (v *NullableListVpcPeersForStack200ResponseLinksSelf) Set(val *ListVpcPeersForStack200ResponseLinksSelf) {
	v.value = val
	v.isSet = true
}

func (v NullableListVpcPeersForStack200ResponseLinksSelf) IsSet() bool {
	return v.isSet
}

func (v *NullableListVpcPeersForStack200ResponseLinksSelf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListVpcPeersForStack200ResponseLinksSelf(val *ListVpcPeersForStack200ResponseLinksSelf) *NullableListVpcPeersForStack200ResponseLinksSelf {
	return &NullableListVpcPeersForStack200ResponseLinksSelf{value: val, isSet: true}
}

func (v NullableListVpcPeersForStack200ResponseLinksSelf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListVpcPeersForStack200ResponseLinksSelf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


