/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListOperationsForService200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOperationsForService200ResponseLinks{}

// ListOperationsForService200ResponseLinks struct for ListOperationsForService200ResponseLinks
type ListOperationsForService200ResponseLinks struct {
	Next *ListOperationsForService200ResponseLinksNext `json:"next,omitempty"`
	Prev *ListOperationsForService200ResponseLinksPrev `json:"prev,omitempty"`
	Self *ListOperationsForService200ResponseLinksSelf `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListOperationsForService200ResponseLinks ListOperationsForService200ResponseLinks

// NewListOperationsForService200ResponseLinks instantiates a new ListOperationsForService200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOperationsForService200ResponseLinks() *ListOperationsForService200ResponseLinks {
	this := ListOperationsForService200ResponseLinks{}
	return &this
}

// NewListOperationsForService200ResponseLinksWithDefaults instantiates a new ListOperationsForService200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOperationsForService200ResponseLinksWithDefaults() *ListOperationsForService200ResponseLinks {
	this := ListOperationsForService200ResponseLinks{}
	return &this
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *ListOperationsForService200ResponseLinks) GetNext() ListOperationsForService200ResponseLinksNext {
	if o == nil || IsNil(o.Next) {
		var ret ListOperationsForService200ResponseLinksNext
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOperationsForService200ResponseLinks) GetNextOk() (*ListOperationsForService200ResponseLinksNext, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *ListOperationsForService200ResponseLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given ListOperationsForService200ResponseLinksNext and assigns it to the Next field.
func (o *ListOperationsForService200ResponseLinks) SetNext(v ListOperationsForService200ResponseLinksNext) {
	o.Next = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *ListOperationsForService200ResponseLinks) GetPrev() ListOperationsForService200ResponseLinksPrev {
	if o == nil || IsNil(o.Prev) {
		var ret ListOperationsForService200ResponseLinksPrev
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOperationsForService200ResponseLinks) GetPrevOk() (*ListOperationsForService200ResponseLinksPrev, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *ListOperationsForService200ResponseLinks) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given ListOperationsForService200ResponseLinksPrev and assigns it to the Prev field.
func (o *ListOperationsForService200ResponseLinks) SetPrev(v ListOperationsForService200ResponseLinksPrev) {
	o.Prev = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ListOperationsForService200ResponseLinks) GetSelf() ListOperationsForService200ResponseLinksSelf {
	if o == nil || IsNil(o.Self) {
		var ret ListOperationsForService200ResponseLinksSelf
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOperationsForService200ResponseLinks) GetSelfOk() (*ListOperationsForService200ResponseLinksSelf, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ListOperationsForService200ResponseLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ListOperationsForService200ResponseLinksSelf and assigns it to the Self field.
func (o *ListOperationsForService200ResponseLinks) SetSelf(v ListOperationsForService200ResponseLinksSelf) {
	o.Self = &v
}

func (o ListOperationsForService200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOperationsForService200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListOperationsForService200ResponseLinks) UnmarshalJSON(data []byte) (err error) {
	varListOperationsForService200ResponseLinks := _ListOperationsForService200ResponseLinks{}

	err = json.Unmarshal(data, &varListOperationsForService200ResponseLinks)

	if err != nil {
		return err
	}

	*o = ListOperationsForService200ResponseLinks(varListOperationsForService200ResponseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "next")
		delete(additionalProperties, "prev")
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListOperationsForService200ResponseLinks struct {
	value *ListOperationsForService200ResponseLinks
	isSet bool
}

func (v NullableListOperationsForService200ResponseLinks) Get() *ListOperationsForService200ResponseLinks {
	return v.value
}

func (v *NullableListOperationsForService200ResponseLinks) Set(val *ListOperationsForService200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableListOperationsForService200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableListOperationsForService200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOperationsForService200ResponseLinks(val *ListOperationsForService200ResponseLinks) *NullableListOperationsForService200ResponseLinks {
	return &NullableListOperationsForService200ResponseLinks{value: val, isSet: true}
}

func (v NullableListOperationsForService200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOperationsForService200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


