/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListImagesForApp200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListImagesForApp200ResponseLinks{}

// ListImagesForApp200ResponseLinks struct for ListImagesForApp200ResponseLinks
type ListImagesForApp200ResponseLinks struct {
	App *ListImagesForApp200ResponseLinksApp `json:"app,omitempty"`
	Next *ListImagesForApp200ResponseLinksNext `json:"next,omitempty"`
	Prev *ListImagesForApp200ResponseLinksPrev `json:"prev,omitempty"`
	Self *ListImagesForApp200ResponseLinksSelf `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListImagesForApp200ResponseLinks ListImagesForApp200ResponseLinks

// NewListImagesForApp200ResponseLinks instantiates a new ListImagesForApp200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListImagesForApp200ResponseLinks() *ListImagesForApp200ResponseLinks {
	this := ListImagesForApp200ResponseLinks{}
	return &this
}

// NewListImagesForApp200ResponseLinksWithDefaults instantiates a new ListImagesForApp200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListImagesForApp200ResponseLinksWithDefaults() *ListImagesForApp200ResponseLinks {
	this := ListImagesForApp200ResponseLinks{}
	return &this
}

// GetApp returns the App field value if set, zero value otherwise.
func (o *ListImagesForApp200ResponseLinks) GetApp() ListImagesForApp200ResponseLinksApp {
	if o == nil || IsNil(o.App) {
		var ret ListImagesForApp200ResponseLinksApp
		return ret
	}
	return *o.App
}

// GetAppOk returns a tuple with the App field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListImagesForApp200ResponseLinks) GetAppOk() (*ListImagesForApp200ResponseLinksApp, bool) {
	if o == nil || IsNil(o.App) {
		return nil, false
	}
	return o.App, true
}

// HasApp returns a boolean if a field has been set.
func (o *ListImagesForApp200ResponseLinks) HasApp() bool {
	if o != nil && !IsNil(o.App) {
		return true
	}

	return false
}

// SetApp gets a reference to the given ListImagesForApp200ResponseLinksApp and assigns it to the App field.
func (o *ListImagesForApp200ResponseLinks) SetApp(v ListImagesForApp200ResponseLinksApp) {
	o.App = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *ListImagesForApp200ResponseLinks) GetNext() ListImagesForApp200ResponseLinksNext {
	if o == nil || IsNil(o.Next) {
		var ret ListImagesForApp200ResponseLinksNext
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListImagesForApp200ResponseLinks) GetNextOk() (*ListImagesForApp200ResponseLinksNext, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *ListImagesForApp200ResponseLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given ListImagesForApp200ResponseLinksNext and assigns it to the Next field.
func (o *ListImagesForApp200ResponseLinks) SetNext(v ListImagesForApp200ResponseLinksNext) {
	o.Next = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *ListImagesForApp200ResponseLinks) GetPrev() ListImagesForApp200ResponseLinksPrev {
	if o == nil || IsNil(o.Prev) {
		var ret ListImagesForApp200ResponseLinksPrev
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListImagesForApp200ResponseLinks) GetPrevOk() (*ListImagesForApp200ResponseLinksPrev, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *ListImagesForApp200ResponseLinks) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given ListImagesForApp200ResponseLinksPrev and assigns it to the Prev field.
func (o *ListImagesForApp200ResponseLinks) SetPrev(v ListImagesForApp200ResponseLinksPrev) {
	o.Prev = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ListImagesForApp200ResponseLinks) GetSelf() ListImagesForApp200ResponseLinksSelf {
	if o == nil || IsNil(o.Self) {
		var ret ListImagesForApp200ResponseLinksSelf
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListImagesForApp200ResponseLinks) GetSelfOk() (*ListImagesForApp200ResponseLinksSelf, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ListImagesForApp200ResponseLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ListImagesForApp200ResponseLinksSelf and assigns it to the Self field.
func (o *ListImagesForApp200ResponseLinks) SetSelf(v ListImagesForApp200ResponseLinksSelf) {
	o.Self = &v
}

func (o ListImagesForApp200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListImagesForApp200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.App) {
		toSerialize["app"] = o.App
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListImagesForApp200ResponseLinks) UnmarshalJSON(data []byte) (err error) {
	varListImagesForApp200ResponseLinks := _ListImagesForApp200ResponseLinks{}

	err = json.Unmarshal(data, &varListImagesForApp200ResponseLinks)

	if err != nil {
		return err
	}

	*o = ListImagesForApp200ResponseLinks(varListImagesForApp200ResponseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "app")
		delete(additionalProperties, "next")
		delete(additionalProperties, "prev")
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListImagesForApp200ResponseLinks struct {
	value *ListImagesForApp200ResponseLinks
	isSet bool
}

func (v NullableListImagesForApp200ResponseLinks) Get() *ListImagesForApp200ResponseLinks {
	return v.value
}

func (v *NullableListImagesForApp200ResponseLinks) Set(val *ListImagesForApp200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableListImagesForApp200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableListImagesForApp200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListImagesForApp200ResponseLinks(val *ListImagesForApp200ResponseLinks) *NullableListImagesForApp200ResponseLinks {
	return &NullableListImagesForApp200ResponseLinks{value: val, isSet: true}
}

func (v NullableListImagesForApp200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListImagesForApp200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


