/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListDatabasesForAccount200ResponseLinksAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDatabasesForAccount200ResponseLinksAccount{}

// ListDatabasesForAccount200ResponseLinksAccount struct for ListDatabasesForAccount200ResponseLinksAccount
type ListDatabasesForAccount200ResponseLinksAccount struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListDatabasesForAccount200ResponseLinksAccount ListDatabasesForAccount200ResponseLinksAccount

// NewListDatabasesForAccount200ResponseLinksAccount instantiates a new ListDatabasesForAccount200ResponseLinksAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDatabasesForAccount200ResponseLinksAccount() *ListDatabasesForAccount200ResponseLinksAccount {
	this := ListDatabasesForAccount200ResponseLinksAccount{}
	return &this
}

// NewListDatabasesForAccount200ResponseLinksAccountWithDefaults instantiates a new ListDatabasesForAccount200ResponseLinksAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDatabasesForAccount200ResponseLinksAccountWithDefaults() *ListDatabasesForAccount200ResponseLinksAccount {
	this := ListDatabasesForAccount200ResponseLinksAccount{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListDatabasesForAccount200ResponseLinksAccount) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDatabasesForAccount200ResponseLinksAccount) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListDatabasesForAccount200ResponseLinksAccount) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListDatabasesForAccount200ResponseLinksAccount) SetHref(v string) {
	o.Href = &v
}

func (o ListDatabasesForAccount200ResponseLinksAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDatabasesForAccount200ResponseLinksAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListDatabasesForAccount200ResponseLinksAccount) UnmarshalJSON(data []byte) (err error) {
	varListDatabasesForAccount200ResponseLinksAccount := _ListDatabasesForAccount200ResponseLinksAccount{}

	err = json.Unmarshal(data, &varListDatabasesForAccount200ResponseLinksAccount)

	if err != nil {
		return err
	}

	*o = ListDatabasesForAccount200ResponseLinksAccount(varListDatabasesForAccount200ResponseLinksAccount)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListDatabasesForAccount200ResponseLinksAccount struct {
	value *ListDatabasesForAccount200ResponseLinksAccount
	isSet bool
}

func (v NullableListDatabasesForAccount200ResponseLinksAccount) Get() *ListDatabasesForAccount200ResponseLinksAccount {
	return v.value
}

func (v *NullableListDatabasesForAccount200ResponseLinksAccount) Set(val *ListDatabasesForAccount200ResponseLinksAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableListDatabasesForAccount200ResponseLinksAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableListDatabasesForAccount200ResponseLinksAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDatabasesForAccount200ResponseLinksAccount(val *ListDatabasesForAccount200ResponseLinksAccount) *NullableListDatabasesForAccount200ResponseLinksAccount {
	return &NullableListDatabasesForAccount200ResponseLinksAccount{value: val, isSet: true}
}

func (v NullableListDatabasesForAccount200ResponseLinksAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDatabasesForAccount200ResponseLinksAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


