/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListLogDrainsForAccount200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListLogDrainsForAccount200ResponseLinks{}

// ListLogDrainsForAccount200ResponseLinks struct for ListLogDrainsForAccount200ResponseLinks
type ListLogDrainsForAccount200ResponseLinks struct {
	Account *ListLogDrainsForAccount200ResponseLinksAccount `json:"account,omitempty"`
	Next *ListLogDrainsForAccount200ResponseLinksNext `json:"next,omitempty"`
	Prev *ListLogDrainsForAccount200ResponseLinksPrev `json:"prev,omitempty"`
	Self *ListLogDrainsForAccount200ResponseLinksSelf `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListLogDrainsForAccount200ResponseLinks ListLogDrainsForAccount200ResponseLinks

// NewListLogDrainsForAccount200ResponseLinks instantiates a new ListLogDrainsForAccount200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListLogDrainsForAccount200ResponseLinks() *ListLogDrainsForAccount200ResponseLinks {
	this := ListLogDrainsForAccount200ResponseLinks{}
	return &this
}

// NewListLogDrainsForAccount200ResponseLinksWithDefaults instantiates a new ListLogDrainsForAccount200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListLogDrainsForAccount200ResponseLinksWithDefaults() *ListLogDrainsForAccount200ResponseLinks {
	this := ListLogDrainsForAccount200ResponseLinks{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *ListLogDrainsForAccount200ResponseLinks) GetAccount() ListLogDrainsForAccount200ResponseLinksAccount {
	if o == nil || IsNil(o.Account) {
		var ret ListLogDrainsForAccount200ResponseLinksAccount
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLogDrainsForAccount200ResponseLinks) GetAccountOk() (*ListLogDrainsForAccount200ResponseLinksAccount, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *ListLogDrainsForAccount200ResponseLinks) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given ListLogDrainsForAccount200ResponseLinksAccount and assigns it to the Account field.
func (o *ListLogDrainsForAccount200ResponseLinks) SetAccount(v ListLogDrainsForAccount200ResponseLinksAccount) {
	o.Account = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *ListLogDrainsForAccount200ResponseLinks) GetNext() ListLogDrainsForAccount200ResponseLinksNext {
	if o == nil || IsNil(o.Next) {
		var ret ListLogDrainsForAccount200ResponseLinksNext
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLogDrainsForAccount200ResponseLinks) GetNextOk() (*ListLogDrainsForAccount200ResponseLinksNext, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *ListLogDrainsForAccount200ResponseLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given ListLogDrainsForAccount200ResponseLinksNext and assigns it to the Next field.
func (o *ListLogDrainsForAccount200ResponseLinks) SetNext(v ListLogDrainsForAccount200ResponseLinksNext) {
	o.Next = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *ListLogDrainsForAccount200ResponseLinks) GetPrev() ListLogDrainsForAccount200ResponseLinksPrev {
	if o == nil || IsNil(o.Prev) {
		var ret ListLogDrainsForAccount200ResponseLinksPrev
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLogDrainsForAccount200ResponseLinks) GetPrevOk() (*ListLogDrainsForAccount200ResponseLinksPrev, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *ListLogDrainsForAccount200ResponseLinks) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given ListLogDrainsForAccount200ResponseLinksPrev and assigns it to the Prev field.
func (o *ListLogDrainsForAccount200ResponseLinks) SetPrev(v ListLogDrainsForAccount200ResponseLinksPrev) {
	o.Prev = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ListLogDrainsForAccount200ResponseLinks) GetSelf() ListLogDrainsForAccount200ResponseLinksSelf {
	if o == nil || IsNil(o.Self) {
		var ret ListLogDrainsForAccount200ResponseLinksSelf
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLogDrainsForAccount200ResponseLinks) GetSelfOk() (*ListLogDrainsForAccount200ResponseLinksSelf, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ListLogDrainsForAccount200ResponseLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ListLogDrainsForAccount200ResponseLinksSelf and assigns it to the Self field.
func (o *ListLogDrainsForAccount200ResponseLinks) SetSelf(v ListLogDrainsForAccount200ResponseLinksSelf) {
	o.Self = &v
}

func (o ListLogDrainsForAccount200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListLogDrainsForAccount200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListLogDrainsForAccount200ResponseLinks) UnmarshalJSON(data []byte) (err error) {
	varListLogDrainsForAccount200ResponseLinks := _ListLogDrainsForAccount200ResponseLinks{}

	err = json.Unmarshal(data, &varListLogDrainsForAccount200ResponseLinks)

	if err != nil {
		return err
	}

	*o = ListLogDrainsForAccount200ResponseLinks(varListLogDrainsForAccount200ResponseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account")
		delete(additionalProperties, "next")
		delete(additionalProperties, "prev")
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListLogDrainsForAccount200ResponseLinks struct {
	value *ListLogDrainsForAccount200ResponseLinks
	isSet bool
}

func (v NullableListLogDrainsForAccount200ResponseLinks) Get() *ListLogDrainsForAccount200ResponseLinks {
	return v.value
}

func (v *NullableListLogDrainsForAccount200ResponseLinks) Set(val *ListLogDrainsForAccount200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableListLogDrainsForAccount200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableListLogDrainsForAccount200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListLogDrainsForAccount200ResponseLinks(val *ListLogDrainsForAccount200ResponseLinks) *NullableListLogDrainsForAccount200ResponseLinks {
	return &NullableListLogDrainsForAccount200ResponseLinks{value: val, isSet: true}
}

func (v NullableListLogDrainsForAccount200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListLogDrainsForAccount200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


