/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ServiceDefinitionLinksSelf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceDefinitionLinksSelf{}

// ServiceDefinitionLinksSelf struct for ServiceDefinitionLinksSelf
type ServiceDefinitionLinksSelf struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServiceDefinitionLinksSelf ServiceDefinitionLinksSelf

// NewServiceDefinitionLinksSelf instantiates a new ServiceDefinitionLinksSelf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceDefinitionLinksSelf() *ServiceDefinitionLinksSelf {
	this := ServiceDefinitionLinksSelf{}
	return &this
}

// NewServiceDefinitionLinksSelfWithDefaults instantiates a new ServiceDefinitionLinksSelf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceDefinitionLinksSelfWithDefaults() *ServiceDefinitionLinksSelf {
	this := ServiceDefinitionLinksSelf{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ServiceDefinitionLinksSelf) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceDefinitionLinksSelf) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ServiceDefinitionLinksSelf) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ServiceDefinitionLinksSelf) SetHref(v string) {
	o.Href = &v
}

func (o ServiceDefinitionLinksSelf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceDefinitionLinksSelf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceDefinitionLinksSelf) UnmarshalJSON(data []byte) (err error) {
	varServiceDefinitionLinksSelf := _ServiceDefinitionLinksSelf{}

	err = json.Unmarshal(data, &varServiceDefinitionLinksSelf)

	if err != nil {
		return err
	}

	*o = ServiceDefinitionLinksSelf(varServiceDefinitionLinksSelf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceDefinitionLinksSelf struct {
	value *ServiceDefinitionLinksSelf
	isSet bool
}

func (v NullableServiceDefinitionLinksSelf) Get() *ServiceDefinitionLinksSelf {
	return v.value
}

func (v *NullableServiceDefinitionLinksSelf) Set(val *ServiceDefinitionLinksSelf) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceDefinitionLinksSelf) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceDefinitionLinksSelf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceDefinitionLinksSelf(val *ServiceDefinitionLinksSelf) *NullableServiceDefinitionLinksSelf {
	return &NullableServiceDefinitionLinksSelf{value: val, isSet: true}
}

func (v NullableServiceDefinitionLinksSelf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceDefinitionLinksSelf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


