/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListVhostsForApp200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListVhostsForApp200ResponseLinks{}

// ListVhostsForApp200ResponseLinks struct for ListVhostsForApp200ResponseLinks
type ListVhostsForApp200ResponseLinks struct {
	App *ListVhostsForApp200ResponseLinksApp `json:"app,omitempty"`
	Service *ListVhostsForApp200ResponseLinksService `json:"service,omitempty"`
	Next *ListVhostsForApp200ResponseLinksNext `json:"next,omitempty"`
	Prev *ListVhostsForApp200ResponseLinksPrev `json:"prev,omitempty"`
	Self *ListVhostsForApp200ResponseLinksSelf `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListVhostsForApp200ResponseLinks ListVhostsForApp200ResponseLinks

// NewListVhostsForApp200ResponseLinks instantiates a new ListVhostsForApp200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListVhostsForApp200ResponseLinks() *ListVhostsForApp200ResponseLinks {
	this := ListVhostsForApp200ResponseLinks{}
	return &this
}

// NewListVhostsForApp200ResponseLinksWithDefaults instantiates a new ListVhostsForApp200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListVhostsForApp200ResponseLinksWithDefaults() *ListVhostsForApp200ResponseLinks {
	this := ListVhostsForApp200ResponseLinks{}
	return &this
}

// GetApp returns the App field value if set, zero value otherwise.
func (o *ListVhostsForApp200ResponseLinks) GetApp() ListVhostsForApp200ResponseLinksApp {
	if o == nil || IsNil(o.App) {
		var ret ListVhostsForApp200ResponseLinksApp
		return ret
	}
	return *o.App
}

// GetAppOk returns a tuple with the App field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVhostsForApp200ResponseLinks) GetAppOk() (*ListVhostsForApp200ResponseLinksApp, bool) {
	if o == nil || IsNil(o.App) {
		return nil, false
	}
	return o.App, true
}

// HasApp returns a boolean if a field has been set.
func (o *ListVhostsForApp200ResponseLinks) HasApp() bool {
	if o != nil && !IsNil(o.App) {
		return true
	}

	return false
}

// SetApp gets a reference to the given ListVhostsForApp200ResponseLinksApp and assigns it to the App field.
func (o *ListVhostsForApp200ResponseLinks) SetApp(v ListVhostsForApp200ResponseLinksApp) {
	o.App = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *ListVhostsForApp200ResponseLinks) GetService() ListVhostsForApp200ResponseLinksService {
	if o == nil || IsNil(o.Service) {
		var ret ListVhostsForApp200ResponseLinksService
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVhostsForApp200ResponseLinks) GetServiceOk() (*ListVhostsForApp200ResponseLinksService, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *ListVhostsForApp200ResponseLinks) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given ListVhostsForApp200ResponseLinksService and assigns it to the Service field.
func (o *ListVhostsForApp200ResponseLinks) SetService(v ListVhostsForApp200ResponseLinksService) {
	o.Service = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *ListVhostsForApp200ResponseLinks) GetNext() ListVhostsForApp200ResponseLinksNext {
	if o == nil || IsNil(o.Next) {
		var ret ListVhostsForApp200ResponseLinksNext
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVhostsForApp200ResponseLinks) GetNextOk() (*ListVhostsForApp200ResponseLinksNext, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *ListVhostsForApp200ResponseLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given ListVhostsForApp200ResponseLinksNext and assigns it to the Next field.
func (o *ListVhostsForApp200ResponseLinks) SetNext(v ListVhostsForApp200ResponseLinksNext) {
	o.Next = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *ListVhostsForApp200ResponseLinks) GetPrev() ListVhostsForApp200ResponseLinksPrev {
	if o == nil || IsNil(o.Prev) {
		var ret ListVhostsForApp200ResponseLinksPrev
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVhostsForApp200ResponseLinks) GetPrevOk() (*ListVhostsForApp200ResponseLinksPrev, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *ListVhostsForApp200ResponseLinks) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given ListVhostsForApp200ResponseLinksPrev and assigns it to the Prev field.
func (o *ListVhostsForApp200ResponseLinks) SetPrev(v ListVhostsForApp200ResponseLinksPrev) {
	o.Prev = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ListVhostsForApp200ResponseLinks) GetSelf() ListVhostsForApp200ResponseLinksSelf {
	if o == nil || IsNil(o.Self) {
		var ret ListVhostsForApp200ResponseLinksSelf
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVhostsForApp200ResponseLinks) GetSelfOk() (*ListVhostsForApp200ResponseLinksSelf, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ListVhostsForApp200ResponseLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ListVhostsForApp200ResponseLinksSelf and assigns it to the Self field.
func (o *ListVhostsForApp200ResponseLinks) SetSelf(v ListVhostsForApp200ResponseLinksSelf) {
	o.Self = &v
}

func (o ListVhostsForApp200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListVhostsForApp200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.App) {
		toSerialize["app"] = o.App
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListVhostsForApp200ResponseLinks) UnmarshalJSON(data []byte) (err error) {
	varListVhostsForApp200ResponseLinks := _ListVhostsForApp200ResponseLinks{}

	err = json.Unmarshal(data, &varListVhostsForApp200ResponseLinks)

	if err != nil {
		return err
	}

	*o = ListVhostsForApp200ResponseLinks(varListVhostsForApp200ResponseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "app")
		delete(additionalProperties, "service")
		delete(additionalProperties, "next")
		delete(additionalProperties, "prev")
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListVhostsForApp200ResponseLinks struct {
	value *ListVhostsForApp200ResponseLinks
	isSet bool
}

func (v NullableListVhostsForApp200ResponseLinks) Get() *ListVhostsForApp200ResponseLinks {
	return v.value
}

func (v *NullableListVhostsForApp200ResponseLinks) Set(val *ListVhostsForApp200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableListVhostsForApp200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableListVhostsForApp200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListVhostsForApp200ResponseLinks(val *ListVhostsForApp200ResponseLinks) *NullableListVhostsForApp200ResponseLinks {
	return &NullableListVhostsForApp200ResponseLinks{value: val, isSet: true}
}

func (v NullableListVhostsForApp200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListVhostsForApp200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


