/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the AppLinksConfigurations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppLinksConfigurations{}

// AppLinksConfigurations struct for AppLinksConfigurations
type AppLinksConfigurations struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AppLinksConfigurations AppLinksConfigurations

// NewAppLinksConfigurations instantiates a new AppLinksConfigurations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppLinksConfigurations() *AppLinksConfigurations {
	this := AppLinksConfigurations{}
	return &this
}

// NewAppLinksConfigurationsWithDefaults instantiates a new AppLinksConfigurations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppLinksConfigurationsWithDefaults() *AppLinksConfigurations {
	this := AppLinksConfigurations{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *AppLinksConfigurations) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppLinksConfigurations) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *AppLinksConfigurations) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *AppLinksConfigurations) SetHref(v string) {
	o.Href = &v
}

func (o AppLinksConfigurations) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppLinksConfigurations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AppLinksConfigurations) UnmarshalJSON(data []byte) (err error) {
	varAppLinksConfigurations := _AppLinksConfigurations{}

	err = json.Unmarshal(data, &varAppLinksConfigurations)

	if err != nil {
		return err
	}

	*o = AppLinksConfigurations(varAppLinksConfigurations)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppLinksConfigurations struct {
	value *AppLinksConfigurations
	isSet bool
}

func (v NullableAppLinksConfigurations) Get() *AppLinksConfigurations {
	return v.value
}

func (v *NullableAppLinksConfigurations) Set(val *AppLinksConfigurations) {
	v.value = val
	v.isSet = true
}

func (v NullableAppLinksConfigurations) IsSet() bool {
	return v.isSet
}

func (v *NullableAppLinksConfigurations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppLinksConfigurations(val *AppLinksConfigurations) *NullableAppLinksConfigurations {
	return &NullableAppLinksConfigurations{value: val, isSet: true}
}

func (v NullableAppLinksConfigurations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppLinksConfigurations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


