/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the AccountLinksLogDrains type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountLinksLogDrains{}

// AccountLinksLogDrains struct for AccountLinksLogDrains
type AccountLinksLogDrains struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AccountLinksLogDrains AccountLinksLogDrains

// NewAccountLinksLogDrains instantiates a new AccountLinksLogDrains object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountLinksLogDrains() *AccountLinksLogDrains {
	this := AccountLinksLogDrains{}
	return &this
}

// NewAccountLinksLogDrainsWithDefaults instantiates a new AccountLinksLogDrains object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountLinksLogDrainsWithDefaults() *AccountLinksLogDrains {
	this := AccountLinksLogDrains{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *AccountLinksLogDrains) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountLinksLogDrains) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *AccountLinksLogDrains) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *AccountLinksLogDrains) SetHref(v string) {
	o.Href = &v
}

func (o AccountLinksLogDrains) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountLinksLogDrains) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccountLinksLogDrains) UnmarshalJSON(data []byte) (err error) {
	varAccountLinksLogDrains := _AccountLinksLogDrains{}

	err = json.Unmarshal(data, &varAccountLinksLogDrains)

	if err != nil {
		return err
	}

	*o = AccountLinksLogDrains(varAccountLinksLogDrains)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccountLinksLogDrains struct {
	value *AccountLinksLogDrains
	isSet bool
}

func (v NullableAccountLinksLogDrains) Get() *AccountLinksLogDrains {
	return v.value
}

func (v *NullableAccountLinksLogDrains) Set(val *AccountLinksLogDrains) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountLinksLogDrains) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountLinksLogDrains) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountLinksLogDrains(val *AccountLinksLogDrains) *NullableAccountLinksLogDrains {
	return &NullableAccountLinksLogDrains{value: val, isSet: true}
}

func (v NullableAccountLinksLogDrains) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountLinksLogDrains) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


