/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListDiskAttachmentsForService200ResponseLinksPrev type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDiskAttachmentsForService200ResponseLinksPrev{}

// ListDiskAttachmentsForService200ResponseLinksPrev struct for ListDiskAttachmentsForService200ResponseLinksPrev
type ListDiskAttachmentsForService200ResponseLinksPrev struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListDiskAttachmentsForService200ResponseLinksPrev ListDiskAttachmentsForService200ResponseLinksPrev

// NewListDiskAttachmentsForService200ResponseLinksPrev instantiates a new ListDiskAttachmentsForService200ResponseLinksPrev object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDiskAttachmentsForService200ResponseLinksPrev() *ListDiskAttachmentsForService200ResponseLinksPrev {
	this := ListDiskAttachmentsForService200ResponseLinksPrev{}
	return &this
}

// NewListDiskAttachmentsForService200ResponseLinksPrevWithDefaults instantiates a new ListDiskAttachmentsForService200ResponseLinksPrev object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDiskAttachmentsForService200ResponseLinksPrevWithDefaults() *ListDiskAttachmentsForService200ResponseLinksPrev {
	this := ListDiskAttachmentsForService200ResponseLinksPrev{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListDiskAttachmentsForService200ResponseLinksPrev) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDiskAttachmentsForService200ResponseLinksPrev) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListDiskAttachmentsForService200ResponseLinksPrev) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListDiskAttachmentsForService200ResponseLinksPrev) SetHref(v string) {
	o.Href = &v
}

func (o ListDiskAttachmentsForService200ResponseLinksPrev) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDiskAttachmentsForService200ResponseLinksPrev) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListDiskAttachmentsForService200ResponseLinksPrev) UnmarshalJSON(data []byte) (err error) {
	varListDiskAttachmentsForService200ResponseLinksPrev := _ListDiskAttachmentsForService200ResponseLinksPrev{}

	err = json.Unmarshal(data, &varListDiskAttachmentsForService200ResponseLinksPrev)

	if err != nil {
		return err
	}

	*o = ListDiskAttachmentsForService200ResponseLinksPrev(varListDiskAttachmentsForService200ResponseLinksPrev)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListDiskAttachmentsForService200ResponseLinksPrev struct {
	value *ListDiskAttachmentsForService200ResponseLinksPrev
	isSet bool
}

func (v NullableListDiskAttachmentsForService200ResponseLinksPrev) Get() *ListDiskAttachmentsForService200ResponseLinksPrev {
	return v.value
}

func (v *NullableListDiskAttachmentsForService200ResponseLinksPrev) Set(val *ListDiskAttachmentsForService200ResponseLinksPrev) {
	v.value = val
	v.isSet = true
}

func (v NullableListDiskAttachmentsForService200ResponseLinksPrev) IsSet() bool {
	return v.isSet
}

func (v *NullableListDiskAttachmentsForService200ResponseLinksPrev) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDiskAttachmentsForService200ResponseLinksPrev(val *ListDiskAttachmentsForService200ResponseLinksPrev) *NullableListDiskAttachmentsForService200ResponseLinksPrev {
	return &NullableListDiskAttachmentsForService200ResponseLinksPrev{value: val, isSet: true}
}

func (v NullableListDiskAttachmentsForService200ResponseLinksPrev) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDiskAttachmentsForService200ResponseLinksPrev) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


