/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the StackLinksAccounts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StackLinksAccounts{}

// StackLinksAccounts struct for StackLinksAccounts
type StackLinksAccounts struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StackLinksAccounts StackLinksAccounts

// NewStackLinksAccounts instantiates a new StackLinksAccounts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackLinksAccounts() *StackLinksAccounts {
	this := StackLinksAccounts{}
	return &this
}

// NewStackLinksAccountsWithDefaults instantiates a new StackLinksAccounts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackLinksAccountsWithDefaults() *StackLinksAccounts {
	this := StackLinksAccounts{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *StackLinksAccounts) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackLinksAccounts) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *StackLinksAccounts) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *StackLinksAccounts) SetHref(v string) {
	o.Href = &v
}

func (o StackLinksAccounts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StackLinksAccounts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StackLinksAccounts) UnmarshalJSON(data []byte) (err error) {
	varStackLinksAccounts := _StackLinksAccounts{}

	err = json.Unmarshal(data, &varStackLinksAccounts)

	if err != nil {
		return err
	}

	*o = StackLinksAccounts(varStackLinksAccounts)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStackLinksAccounts struct {
	value *StackLinksAccounts
	isSet bool
}

func (v NullableStackLinksAccounts) Get() *StackLinksAccounts {
	return v.value
}

func (v *NullableStackLinksAccounts) Set(val *StackLinksAccounts) {
	v.value = val
	v.isSet = true
}

func (v NullableStackLinksAccounts) IsSet() bool {
	return v.isSet
}

func (v *NullableStackLinksAccounts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackLinksAccounts(val *StackLinksAccounts) *NullableStackLinksAccounts {
	return &NullableStackLinksAccounts{value: val, isSet: true}
}

func (v NullableStackLinksAccounts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackLinksAccounts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


