/*
Aptible API v1

REST API for the core Aptible platform.

API version: v1
Contact: support@aptible.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the LlmKeyCurrentUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LlmKeyCurrentUsage{}

// LlmKeyCurrentUsage Month-to-date usage metrics for this key
type LlmKeyCurrentUsage struct {
	// Total spend in USD
	Spend *float32 `json:"spend,omitempty"`
	// Total input (prompt) tokens
	InputTokens *int32 `json:"input_tokens,omitempty"`
	// Total output (completion) tokens
	OutputTokens *int32 `json:"output_tokens,omitempty"`
	// Total successful API requests
	SuccessfulRequests *int32 `json:"successful_requests,omitempty"`
	// Total failed API requests
	FailedRequests *int32 `json:"failed_requests,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LlmKeyCurrentUsage LlmKeyCurrentUsage

// NewLlmKeyCurrentUsage instantiates a new LlmKeyCurrentUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLlmKeyCurrentUsage() *LlmKeyCurrentUsage {
	this := LlmKeyCurrentUsage{}
	return &this
}

// NewLlmKeyCurrentUsageWithDefaults instantiates a new LlmKeyCurrentUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLlmKeyCurrentUsageWithDefaults() *LlmKeyCurrentUsage {
	this := LlmKeyCurrentUsage{}
	return &this
}

// GetSpend returns the Spend field value if set, zero value otherwise.
func (o *LlmKeyCurrentUsage) GetSpend() float32 {
	if o == nil || IsNil(o.Spend) {
		var ret float32
		return ret
	}
	return *o.Spend
}

// GetSpendOk returns a tuple with the Spend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LlmKeyCurrentUsage) GetSpendOk() (*float32, bool) {
	if o == nil || IsNil(o.Spend) {
		return nil, false
	}
	return o.Spend, true
}

// HasSpend returns a boolean if a field has been set.
func (o *LlmKeyCurrentUsage) HasSpend() bool {
	if o != nil && !IsNil(o.Spend) {
		return true
	}

	return false
}

// SetSpend gets a reference to the given float32 and assigns it to the Spend field.
func (o *LlmKeyCurrentUsage) SetSpend(v float32) {
	o.Spend = &v
}

// GetInputTokens returns the InputTokens field value if set, zero value otherwise.
func (o *LlmKeyCurrentUsage) GetInputTokens() int32 {
	if o == nil || IsNil(o.InputTokens) {
		var ret int32
		return ret
	}
	return *o.InputTokens
}

// GetInputTokensOk returns a tuple with the InputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LlmKeyCurrentUsage) GetInputTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.InputTokens) {
		return nil, false
	}
	return o.InputTokens, true
}

// HasInputTokens returns a boolean if a field has been set.
func (o *LlmKeyCurrentUsage) HasInputTokens() bool {
	if o != nil && !IsNil(o.InputTokens) {
		return true
	}

	return false
}

// SetInputTokens gets a reference to the given int32 and assigns it to the InputTokens field.
func (o *LlmKeyCurrentUsage) SetInputTokens(v int32) {
	o.InputTokens = &v
}

// GetOutputTokens returns the OutputTokens field value if set, zero value otherwise.
func (o *LlmKeyCurrentUsage) GetOutputTokens() int32 {
	if o == nil || IsNil(o.OutputTokens) {
		var ret int32
		return ret
	}
	return *o.OutputTokens
}

// GetOutputTokensOk returns a tuple with the OutputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LlmKeyCurrentUsage) GetOutputTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.OutputTokens) {
		return nil, false
	}
	return o.OutputTokens, true
}

// HasOutputTokens returns a boolean if a field has been set.
func (o *LlmKeyCurrentUsage) HasOutputTokens() bool {
	if o != nil && !IsNil(o.OutputTokens) {
		return true
	}

	return false
}

// SetOutputTokens gets a reference to the given int32 and assigns it to the OutputTokens field.
func (o *LlmKeyCurrentUsage) SetOutputTokens(v int32) {
	o.OutputTokens = &v
}

// GetSuccessfulRequests returns the SuccessfulRequests field value if set, zero value otherwise.
func (o *LlmKeyCurrentUsage) GetSuccessfulRequests() int32 {
	if o == nil || IsNil(o.SuccessfulRequests) {
		var ret int32
		return ret
	}
	return *o.SuccessfulRequests
}

// GetSuccessfulRequestsOk returns a tuple with the SuccessfulRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LlmKeyCurrentUsage) GetSuccessfulRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.SuccessfulRequests) {
		return nil, false
	}
	return o.SuccessfulRequests, true
}

// HasSuccessfulRequests returns a boolean if a field has been set.
func (o *LlmKeyCurrentUsage) HasSuccessfulRequests() bool {
	if o != nil && !IsNil(o.SuccessfulRequests) {
		return true
	}

	return false
}

// SetSuccessfulRequests gets a reference to the given int32 and assigns it to the SuccessfulRequests field.
func (o *LlmKeyCurrentUsage) SetSuccessfulRequests(v int32) {
	o.SuccessfulRequests = &v
}

// GetFailedRequests returns the FailedRequests field value if set, zero value otherwise.
func (o *LlmKeyCurrentUsage) GetFailedRequests() int32 {
	if o == nil || IsNil(o.FailedRequests) {
		var ret int32
		return ret
	}
	return *o.FailedRequests
}

// GetFailedRequestsOk returns a tuple with the FailedRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LlmKeyCurrentUsage) GetFailedRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.FailedRequests) {
		return nil, false
	}
	return o.FailedRequests, true
}

// HasFailedRequests returns a boolean if a field has been set.
func (o *LlmKeyCurrentUsage) HasFailedRequests() bool {
	if o != nil && !IsNil(o.FailedRequests) {
		return true
	}

	return false
}

// SetFailedRequests gets a reference to the given int32 and assigns it to the FailedRequests field.
func (o *LlmKeyCurrentUsage) SetFailedRequests(v int32) {
	o.FailedRequests = &v
}

func (o LlmKeyCurrentUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LlmKeyCurrentUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Spend) {
		toSerialize["spend"] = o.Spend
	}
	if !IsNil(o.InputTokens) {
		toSerialize["input_tokens"] = o.InputTokens
	}
	if !IsNil(o.OutputTokens) {
		toSerialize["output_tokens"] = o.OutputTokens
	}
	if !IsNil(o.SuccessfulRequests) {
		toSerialize["successful_requests"] = o.SuccessfulRequests
	}
	if !IsNil(o.FailedRequests) {
		toSerialize["failed_requests"] = o.FailedRequests
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LlmKeyCurrentUsage) UnmarshalJSON(data []byte) (err error) {
	varLlmKeyCurrentUsage := _LlmKeyCurrentUsage{}

	err = json.Unmarshal(data, &varLlmKeyCurrentUsage)

	if err != nil {
		return err
	}

	*o = LlmKeyCurrentUsage(varLlmKeyCurrentUsage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "spend")
		delete(additionalProperties, "input_tokens")
		delete(additionalProperties, "output_tokens")
		delete(additionalProperties, "successful_requests")
		delete(additionalProperties, "failed_requests")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLlmKeyCurrentUsage struct {
	value *LlmKeyCurrentUsage
	isSet bool
}

func (v NullableLlmKeyCurrentUsage) Get() *LlmKeyCurrentUsage {
	return v.value
}

func (v *NullableLlmKeyCurrentUsage) Set(val *LlmKeyCurrentUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableLlmKeyCurrentUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableLlmKeyCurrentUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLlmKeyCurrentUsage(val *LlmKeyCurrentUsage) *NullableLlmKeyCurrentUsage {
	return &NullableLlmKeyCurrentUsage{value: val, isSet: true}
}

func (v NullableLlmKeyCurrentUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLlmKeyCurrentUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


