/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the WidgetLinksDashboard type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WidgetLinksDashboard{}

// WidgetLinksDashboard struct for WidgetLinksDashboard
type WidgetLinksDashboard struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WidgetLinksDashboard WidgetLinksDashboard

// NewWidgetLinksDashboard instantiates a new WidgetLinksDashboard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWidgetLinksDashboard() *WidgetLinksDashboard {
	this := WidgetLinksDashboard{}
	return &this
}

// NewWidgetLinksDashboardWithDefaults instantiates a new WidgetLinksDashboard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWidgetLinksDashboardWithDefaults() *WidgetLinksDashboard {
	this := WidgetLinksDashboard{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *WidgetLinksDashboard) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WidgetLinksDashboard) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *WidgetLinksDashboard) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *WidgetLinksDashboard) SetHref(v string) {
	o.Href = &v
}

func (o WidgetLinksDashboard) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WidgetLinksDashboard) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WidgetLinksDashboard) UnmarshalJSON(data []byte) (err error) {
	varWidgetLinksDashboard := _WidgetLinksDashboard{}

	err = json.Unmarshal(data, &varWidgetLinksDashboard)

	if err != nil {
		return err
	}

	*o = WidgetLinksDashboard(varWidgetLinksDashboard)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWidgetLinksDashboard struct {
	value *WidgetLinksDashboard
	isSet bool
}

func (v NullableWidgetLinksDashboard) Get() *WidgetLinksDashboard {
	return v.value
}

func (v *NullableWidgetLinksDashboard) Set(val *WidgetLinksDashboard) {
	v.value = val
	v.isSet = true
}

func (v NullableWidgetLinksDashboard) IsSet() bool {
	return v.isSet
}

func (v *NullableWidgetLinksDashboard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWidgetLinksDashboard(val *WidgetLinksDashboard) *NullableWidgetLinksDashboard {
	return &NullableWidgetLinksDashboard{value: val, isSet: true}
}

func (v NullableWidgetLinksDashboard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWidgetLinksDashboard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


