/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListVhostsForService200ResponseLinksNext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListVhostsForService200ResponseLinksNext{}

// ListVhostsForService200ResponseLinksNext struct for ListVhostsForService200ResponseLinksNext
type ListVhostsForService200ResponseLinksNext struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListVhostsForService200ResponseLinksNext ListVhostsForService200ResponseLinksNext

// NewListVhostsForService200ResponseLinksNext instantiates a new ListVhostsForService200ResponseLinksNext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListVhostsForService200ResponseLinksNext() *ListVhostsForService200ResponseLinksNext {
	this := ListVhostsForService200ResponseLinksNext{}
	return &this
}

// NewListVhostsForService200ResponseLinksNextWithDefaults instantiates a new ListVhostsForService200ResponseLinksNext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListVhostsForService200ResponseLinksNextWithDefaults() *ListVhostsForService200ResponseLinksNext {
	this := ListVhostsForService200ResponseLinksNext{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListVhostsForService200ResponseLinksNext) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVhostsForService200ResponseLinksNext) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListVhostsForService200ResponseLinksNext) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListVhostsForService200ResponseLinksNext) SetHref(v string) {
	o.Href = &v
}

func (o ListVhostsForService200ResponseLinksNext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListVhostsForService200ResponseLinksNext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListVhostsForService200ResponseLinksNext) UnmarshalJSON(data []byte) (err error) {
	varListVhostsForService200ResponseLinksNext := _ListVhostsForService200ResponseLinksNext{}

	err = json.Unmarshal(data, &varListVhostsForService200ResponseLinksNext)

	if err != nil {
		return err
	}

	*o = ListVhostsForService200ResponseLinksNext(varListVhostsForService200ResponseLinksNext)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListVhostsForService200ResponseLinksNext struct {
	value *ListVhostsForService200ResponseLinksNext
	isSet bool
}

func (v NullableListVhostsForService200ResponseLinksNext) Get() *ListVhostsForService200ResponseLinksNext {
	return v.value
}

func (v *NullableListVhostsForService200ResponseLinksNext) Set(val *ListVhostsForService200ResponseLinksNext) {
	v.value = val
	v.isSet = true
}

func (v NullableListVhostsForService200ResponseLinksNext) IsSet() bool {
	return v.isSet
}

func (v *NullableListVhostsForService200ResponseLinksNext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListVhostsForService200ResponseLinksNext(val *ListVhostsForService200ResponseLinksNext) *NullableListVhostsForService200ResponseLinksNext {
	return &NullableListVhostsForService200ResponseLinksNext{value: val, isSet: true}
}

func (v NullableListVhostsForService200ResponseLinksNext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListVhostsForService200ResponseLinksNext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


