/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the DatabaseLinksSelf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatabaseLinksSelf{}

// DatabaseLinksSelf struct for DatabaseLinksSelf
type DatabaseLinksSelf struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DatabaseLinksSelf DatabaseLinksSelf

// NewDatabaseLinksSelf instantiates a new DatabaseLinksSelf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatabaseLinksSelf() *DatabaseLinksSelf {
	this := DatabaseLinksSelf{}
	return &this
}

// NewDatabaseLinksSelfWithDefaults instantiates a new DatabaseLinksSelf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatabaseLinksSelfWithDefaults() *DatabaseLinksSelf {
	this := DatabaseLinksSelf{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *DatabaseLinksSelf) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabaseLinksSelf) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *DatabaseLinksSelf) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *DatabaseLinksSelf) SetHref(v string) {
	o.Href = &v
}

func (o DatabaseLinksSelf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatabaseLinksSelf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DatabaseLinksSelf) UnmarshalJSON(data []byte) (err error) {
	varDatabaseLinksSelf := _DatabaseLinksSelf{}

	err = json.Unmarshal(data, &varDatabaseLinksSelf)

	if err != nil {
		return err
	}

	*o = DatabaseLinksSelf(varDatabaseLinksSelf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDatabaseLinksSelf struct {
	value *DatabaseLinksSelf
	isSet bool
}

func (v NullableDatabaseLinksSelf) Get() *DatabaseLinksSelf {
	return v.value
}

func (v *NullableDatabaseLinksSelf) Set(val *DatabaseLinksSelf) {
	v.value = val
	v.isSet = true
}

func (v NullableDatabaseLinksSelf) IsSet() bool {
	return v.isSet
}

func (v *NullableDatabaseLinksSelf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatabaseLinksSelf(val *DatabaseLinksSelf) *NullableDatabaseLinksSelf {
	return &NullableDatabaseLinksSelf{value: val, isSet: true}
}

func (v NullableDatabaseLinksSelf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatabaseLinksSelf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


