/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListActivityReportsForAccount200ResponseLinksAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListActivityReportsForAccount200ResponseLinksAccount{}

// ListActivityReportsForAccount200ResponseLinksAccount struct for ListActivityReportsForAccount200ResponseLinksAccount
type ListActivityReportsForAccount200ResponseLinksAccount struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListActivityReportsForAccount200ResponseLinksAccount ListActivityReportsForAccount200ResponseLinksAccount

// NewListActivityReportsForAccount200ResponseLinksAccount instantiates a new ListActivityReportsForAccount200ResponseLinksAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListActivityReportsForAccount200ResponseLinksAccount() *ListActivityReportsForAccount200ResponseLinksAccount {
	this := ListActivityReportsForAccount200ResponseLinksAccount{}
	return &this
}

// NewListActivityReportsForAccount200ResponseLinksAccountWithDefaults instantiates a new ListActivityReportsForAccount200ResponseLinksAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListActivityReportsForAccount200ResponseLinksAccountWithDefaults() *ListActivityReportsForAccount200ResponseLinksAccount {
	this := ListActivityReportsForAccount200ResponseLinksAccount{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListActivityReportsForAccount200ResponseLinksAccount) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListActivityReportsForAccount200ResponseLinksAccount) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListActivityReportsForAccount200ResponseLinksAccount) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListActivityReportsForAccount200ResponseLinksAccount) SetHref(v string) {
	o.Href = &v
}

func (o ListActivityReportsForAccount200ResponseLinksAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListActivityReportsForAccount200ResponseLinksAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListActivityReportsForAccount200ResponseLinksAccount) UnmarshalJSON(data []byte) (err error) {
	varListActivityReportsForAccount200ResponseLinksAccount := _ListActivityReportsForAccount200ResponseLinksAccount{}

	err = json.Unmarshal(data, &varListActivityReportsForAccount200ResponseLinksAccount)

	if err != nil {
		return err
	}

	*o = ListActivityReportsForAccount200ResponseLinksAccount(varListActivityReportsForAccount200ResponseLinksAccount)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListActivityReportsForAccount200ResponseLinksAccount struct {
	value *ListActivityReportsForAccount200ResponseLinksAccount
	isSet bool
}

func (v NullableListActivityReportsForAccount200ResponseLinksAccount) Get() *ListActivityReportsForAccount200ResponseLinksAccount {
	return v.value
}

func (v *NullableListActivityReportsForAccount200ResponseLinksAccount) Set(val *ListActivityReportsForAccount200ResponseLinksAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableListActivityReportsForAccount200ResponseLinksAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableListActivityReportsForAccount200ResponseLinksAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListActivityReportsForAccount200ResponseLinksAccount(val *ListActivityReportsForAccount200ResponseLinksAccount) *NullableListActivityReportsForAccount200ResponseLinksAccount {
	return &NullableListActivityReportsForAccount200ResponseLinksAccount{value: val, isSet: true}
}

func (v NullableListActivityReportsForAccount200ResponseLinksAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListActivityReportsForAccount200ResponseLinksAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


