/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListStacks200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListStacks200ResponseLinks{}

// ListStacks200ResponseLinks struct for ListStacks200ResponseLinks
type ListStacks200ResponseLinks struct {
	Next *ListStacks200ResponseLinksNext `json:"next,omitempty"`
	Prev *ListStacks200ResponseLinksPrev `json:"prev,omitempty"`
	Self *ListStacks200ResponseLinksSelf `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListStacks200ResponseLinks ListStacks200ResponseLinks

// NewListStacks200ResponseLinks instantiates a new ListStacks200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListStacks200ResponseLinks() *ListStacks200ResponseLinks {
	this := ListStacks200ResponseLinks{}
	return &this
}

// NewListStacks200ResponseLinksWithDefaults instantiates a new ListStacks200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListStacks200ResponseLinksWithDefaults() *ListStacks200ResponseLinks {
	this := ListStacks200ResponseLinks{}
	return &this
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *ListStacks200ResponseLinks) GetNext() ListStacks200ResponseLinksNext {
	if o == nil || IsNil(o.Next) {
		var ret ListStacks200ResponseLinksNext
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListStacks200ResponseLinks) GetNextOk() (*ListStacks200ResponseLinksNext, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *ListStacks200ResponseLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given ListStacks200ResponseLinksNext and assigns it to the Next field.
func (o *ListStacks200ResponseLinks) SetNext(v ListStacks200ResponseLinksNext) {
	o.Next = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *ListStacks200ResponseLinks) GetPrev() ListStacks200ResponseLinksPrev {
	if o == nil || IsNil(o.Prev) {
		var ret ListStacks200ResponseLinksPrev
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListStacks200ResponseLinks) GetPrevOk() (*ListStacks200ResponseLinksPrev, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *ListStacks200ResponseLinks) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given ListStacks200ResponseLinksPrev and assigns it to the Prev field.
func (o *ListStacks200ResponseLinks) SetPrev(v ListStacks200ResponseLinksPrev) {
	o.Prev = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ListStacks200ResponseLinks) GetSelf() ListStacks200ResponseLinksSelf {
	if o == nil || IsNil(o.Self) {
		var ret ListStacks200ResponseLinksSelf
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListStacks200ResponseLinks) GetSelfOk() (*ListStacks200ResponseLinksSelf, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ListStacks200ResponseLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ListStacks200ResponseLinksSelf and assigns it to the Self field.
func (o *ListStacks200ResponseLinks) SetSelf(v ListStacks200ResponseLinksSelf) {
	o.Self = &v
}

func (o ListStacks200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListStacks200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListStacks200ResponseLinks) UnmarshalJSON(data []byte) (err error) {
	varListStacks200ResponseLinks := _ListStacks200ResponseLinks{}

	err = json.Unmarshal(data, &varListStacks200ResponseLinks)

	if err != nil {
		return err
	}

	*o = ListStacks200ResponseLinks(varListStacks200ResponseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "next")
		delete(additionalProperties, "prev")
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListStacks200ResponseLinks struct {
	value *ListStacks200ResponseLinks
	isSet bool
}

func (v NullableListStacks200ResponseLinks) Get() *ListStacks200ResponseLinks {
	return v.value
}

func (v *NullableListStacks200ResponseLinks) Set(val *ListStacks200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableListStacks200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableListStacks200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListStacks200ResponseLinks(val *ListStacks200ResponseLinks) *NullableListStacks200ResponseLinks {
	return &NullableListStacks200ResponseLinks{value: val, isSet: true}
}

func (v NullableListStacks200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListStacks200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


