/*
Aptible API v1

REST API for the core Aptible platform.

API version: v1
Contact: support@aptible.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the CreateClaimForTypeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateClaimForTypeRequest{}

// CreateClaimForTypeRequest struct for CreateClaimForTypeRequest
type CreateClaimForTypeRequest struct {
	Handle *string `json:"handle,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateClaimForTypeRequest CreateClaimForTypeRequest

// NewCreateClaimForTypeRequest instantiates a new CreateClaimForTypeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClaimForTypeRequest() *CreateClaimForTypeRequest {
	this := CreateClaimForTypeRequest{}
	return &this
}

// NewCreateClaimForTypeRequestWithDefaults instantiates a new CreateClaimForTypeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClaimForTypeRequestWithDefaults() *CreateClaimForTypeRequest {
	this := CreateClaimForTypeRequest{}
	return &this
}

// GetHandle returns the Handle field value if set, zero value otherwise.
func (o *CreateClaimForTypeRequest) GetHandle() string {
	if o == nil || IsNil(o.Handle) {
		var ret string
		return ret
	}
	return *o.Handle
}

// GetHandleOk returns a tuple with the Handle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClaimForTypeRequest) GetHandleOk() (*string, bool) {
	if o == nil || IsNil(o.Handle) {
		return nil, false
	}
	return o.Handle, true
}

// HasHandle returns a boolean if a field has been set.
func (o *CreateClaimForTypeRequest) HasHandle() bool {
	if o != nil && !IsNil(o.Handle) {
		return true
	}

	return false
}

// SetHandle gets a reference to the given string and assigns it to the Handle field.
func (o *CreateClaimForTypeRequest) SetHandle(v string) {
	o.Handle = &v
}

func (o CreateClaimForTypeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateClaimForTypeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Handle) {
		toSerialize["handle"] = o.Handle
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateClaimForTypeRequest) UnmarshalJSON(data []byte) (err error) {
	varCreateClaimForTypeRequest := _CreateClaimForTypeRequest{}

	err = json.Unmarshal(data, &varCreateClaimForTypeRequest)

	if err != nil {
		return err
	}

	*o = CreateClaimForTypeRequest(varCreateClaimForTypeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "handle")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateClaimForTypeRequest struct {
	value *CreateClaimForTypeRequest
	isSet bool
}

func (v NullableCreateClaimForTypeRequest) Get() *CreateClaimForTypeRequest {
	return v.value
}

func (v *NullableCreateClaimForTypeRequest) Set(val *CreateClaimForTypeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClaimForTypeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClaimForTypeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClaimForTypeRequest(val *CreateClaimForTypeRequest) *NullableCreateClaimForTypeRequest {
	return &NullableCreateClaimForTypeRequest{value: val, isSet: true}
}

func (v NullableCreateClaimForTypeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClaimForTypeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


