/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListOperationsForMetricDrain200ResponseLinksPrev type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOperationsForMetricDrain200ResponseLinksPrev{}

// ListOperationsForMetricDrain200ResponseLinksPrev struct for ListOperationsForMetricDrain200ResponseLinksPrev
type ListOperationsForMetricDrain200ResponseLinksPrev struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListOperationsForMetricDrain200ResponseLinksPrev ListOperationsForMetricDrain200ResponseLinksPrev

// NewListOperationsForMetricDrain200ResponseLinksPrev instantiates a new ListOperationsForMetricDrain200ResponseLinksPrev object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOperationsForMetricDrain200ResponseLinksPrev() *ListOperationsForMetricDrain200ResponseLinksPrev {
	this := ListOperationsForMetricDrain200ResponseLinksPrev{}
	return &this
}

// NewListOperationsForMetricDrain200ResponseLinksPrevWithDefaults instantiates a new ListOperationsForMetricDrain200ResponseLinksPrev object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOperationsForMetricDrain200ResponseLinksPrevWithDefaults() *ListOperationsForMetricDrain200ResponseLinksPrev {
	this := ListOperationsForMetricDrain200ResponseLinksPrev{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListOperationsForMetricDrain200ResponseLinksPrev) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOperationsForMetricDrain200ResponseLinksPrev) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListOperationsForMetricDrain200ResponseLinksPrev) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListOperationsForMetricDrain200ResponseLinksPrev) SetHref(v string) {
	o.Href = &v
}

func (o ListOperationsForMetricDrain200ResponseLinksPrev) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOperationsForMetricDrain200ResponseLinksPrev) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListOperationsForMetricDrain200ResponseLinksPrev) UnmarshalJSON(data []byte) (err error) {
	varListOperationsForMetricDrain200ResponseLinksPrev := _ListOperationsForMetricDrain200ResponseLinksPrev{}

	err = json.Unmarshal(data, &varListOperationsForMetricDrain200ResponseLinksPrev)

	if err != nil {
		return err
	}

	*o = ListOperationsForMetricDrain200ResponseLinksPrev(varListOperationsForMetricDrain200ResponseLinksPrev)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListOperationsForMetricDrain200ResponseLinksPrev struct {
	value *ListOperationsForMetricDrain200ResponseLinksPrev
	isSet bool
}

func (v NullableListOperationsForMetricDrain200ResponseLinksPrev) Get() *ListOperationsForMetricDrain200ResponseLinksPrev {
	return v.value
}

func (v *NullableListOperationsForMetricDrain200ResponseLinksPrev) Set(val *ListOperationsForMetricDrain200ResponseLinksPrev) {
	v.value = val
	v.isSet = true
}

func (v NullableListOperationsForMetricDrain200ResponseLinksPrev) IsSet() bool {
	return v.isSet
}

func (v *NullableListOperationsForMetricDrain200ResponseLinksPrev) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOperationsForMetricDrain200ResponseLinksPrev(val *ListOperationsForMetricDrain200ResponseLinksPrev) *NullableListOperationsForMetricDrain200ResponseLinksPrev {
	return &NullableListOperationsForMetricDrain200ResponseLinksPrev{value: val, isSet: true}
}

func (v NullableListOperationsForMetricDrain200ResponseLinksPrev) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOperationsForMetricDrain200ResponseLinksPrev) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


