/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListOperationsForService200ResponseLinksNext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOperationsForService200ResponseLinksNext{}

// ListOperationsForService200ResponseLinksNext struct for ListOperationsForService200ResponseLinksNext
type ListOperationsForService200ResponseLinksNext struct {
	Href *string `json:"href,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListOperationsForService200ResponseLinksNext ListOperationsForService200ResponseLinksNext

// NewListOperationsForService200ResponseLinksNext instantiates a new ListOperationsForService200ResponseLinksNext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOperationsForService200ResponseLinksNext() *ListOperationsForService200ResponseLinksNext {
	this := ListOperationsForService200ResponseLinksNext{}
	return &this
}

// NewListOperationsForService200ResponseLinksNextWithDefaults instantiates a new ListOperationsForService200ResponseLinksNext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOperationsForService200ResponseLinksNextWithDefaults() *ListOperationsForService200ResponseLinksNext {
	this := ListOperationsForService200ResponseLinksNext{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ListOperationsForService200ResponseLinksNext) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOperationsForService200ResponseLinksNext) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ListOperationsForService200ResponseLinksNext) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ListOperationsForService200ResponseLinksNext) SetHref(v string) {
	o.Href = &v
}

func (o ListOperationsForService200ResponseLinksNext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOperationsForService200ResponseLinksNext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListOperationsForService200ResponseLinksNext) UnmarshalJSON(data []byte) (err error) {
	varListOperationsForService200ResponseLinksNext := _ListOperationsForService200ResponseLinksNext{}

	err = json.Unmarshal(data, &varListOperationsForService200ResponseLinksNext)

	if err != nil {
		return err
	}

	*o = ListOperationsForService200ResponseLinksNext(varListOperationsForService200ResponseLinksNext)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "href")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListOperationsForService200ResponseLinksNext struct {
	value *ListOperationsForService200ResponseLinksNext
	isSet bool
}

func (v NullableListOperationsForService200ResponseLinksNext) Get() *ListOperationsForService200ResponseLinksNext {
	return v.value
}

func (v *NullableListOperationsForService200ResponseLinksNext) Set(val *ListOperationsForService200ResponseLinksNext) {
	v.value = val
	v.isSet = true
}

func (v NullableListOperationsForService200ResponseLinksNext) IsSet() bool {
	return v.isSet
}

func (v *NullableListOperationsForService200ResponseLinksNext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOperationsForService200ResponseLinksNext(val *ListOperationsForService200ResponseLinksNext) *NullableListOperationsForService200ResponseLinksNext {
	return &NullableListOperationsForService200ResponseLinksNext{value: val, isSet: true}
}

func (v NullableListOperationsForService200ResponseLinksNext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOperationsForService200ResponseLinksNext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


