/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListAppsForSource200ResponseEmbedded type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAppsForSource200ResponseEmbedded{}

// ListAppsForSource200ResponseEmbedded struct for ListAppsForSource200ResponseEmbedded
type ListAppsForSource200ResponseEmbedded struct {
	Apps []App `json:"apps,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListAppsForSource200ResponseEmbedded ListAppsForSource200ResponseEmbedded

// NewListAppsForSource200ResponseEmbedded instantiates a new ListAppsForSource200ResponseEmbedded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAppsForSource200ResponseEmbedded() *ListAppsForSource200ResponseEmbedded {
	this := ListAppsForSource200ResponseEmbedded{}
	return &this
}

// NewListAppsForSource200ResponseEmbeddedWithDefaults instantiates a new ListAppsForSource200ResponseEmbedded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAppsForSource200ResponseEmbeddedWithDefaults() *ListAppsForSource200ResponseEmbedded {
	this := ListAppsForSource200ResponseEmbedded{}
	return &this
}

// GetApps returns the Apps field value if set, zero value otherwise.
func (o *ListAppsForSource200ResponseEmbedded) GetApps() []App {
	if o == nil || IsNil(o.Apps) {
		var ret []App
		return ret
	}
	return o.Apps
}

// GetAppsOk returns a tuple with the Apps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAppsForSource200ResponseEmbedded) GetAppsOk() ([]App, bool) {
	if o == nil || IsNil(o.Apps) {
		return nil, false
	}
	return o.Apps, true
}

// HasApps returns a boolean if a field has been set.
func (o *ListAppsForSource200ResponseEmbedded) HasApps() bool {
	if o != nil && !IsNil(o.Apps) {
		return true
	}

	return false
}

// SetApps gets a reference to the given []App and assigns it to the Apps field.
func (o *ListAppsForSource200ResponseEmbedded) SetApps(v []App) {
	o.Apps = v
}

func (o ListAppsForSource200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAppsForSource200ResponseEmbedded) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Apps) {
		toSerialize["apps"] = o.Apps
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAppsForSource200ResponseEmbedded) UnmarshalJSON(data []byte) (err error) {
	varListAppsForSource200ResponseEmbedded := _ListAppsForSource200ResponseEmbedded{}

	err = json.Unmarshal(data, &varListAppsForSource200ResponseEmbedded)

	if err != nil {
		return err
	}

	*o = ListAppsForSource200ResponseEmbedded(varListAppsForSource200ResponseEmbedded)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "apps")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAppsForSource200ResponseEmbedded struct {
	value *ListAppsForSource200ResponseEmbedded
	isSet bool
}

func (v NullableListAppsForSource200ResponseEmbedded) Get() *ListAppsForSource200ResponseEmbedded {
	return v.value
}

func (v *NullableListAppsForSource200ResponseEmbedded) Set(val *ListAppsForSource200ResponseEmbedded) {
	v.value = val
	v.isSet = true
}

func (v NullableListAppsForSource200ResponseEmbedded) IsSet() bool {
	return v.isSet
}

func (v *NullableListAppsForSource200ResponseEmbedded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAppsForSource200ResponseEmbedded(val *ListAppsForSource200ResponseEmbedded) *NullableListAppsForSource200ResponseEmbedded {
	return &NullableListAppsForSource200ResponseEmbedded{value: val, isSet: true}
}

func (v NullableListAppsForSource200ResponseEmbedded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAppsForSource200ResponseEmbedded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


