/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListBackupRetentionPoliciesForAccount200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListBackupRetentionPoliciesForAccount200ResponseLinks{}

// ListBackupRetentionPoliciesForAccount200ResponseLinks struct for ListBackupRetentionPoliciesForAccount200ResponseLinks
type ListBackupRetentionPoliciesForAccount200ResponseLinks struct {
	Account *ListBackupRetentionPoliciesForAccount200ResponseLinksAccount `json:"account,omitempty"`
	Next *ListBackupRetentionPoliciesForAccount200ResponseLinksNext `json:"next,omitempty"`
	Prev *ListBackupRetentionPoliciesForAccount200ResponseLinksPrev `json:"prev,omitempty"`
	Self *ListBackupRetentionPoliciesForAccount200ResponseLinksSelf `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListBackupRetentionPoliciesForAccount200ResponseLinks ListBackupRetentionPoliciesForAccount200ResponseLinks

// NewListBackupRetentionPoliciesForAccount200ResponseLinks instantiates a new ListBackupRetentionPoliciesForAccount200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListBackupRetentionPoliciesForAccount200ResponseLinks() *ListBackupRetentionPoliciesForAccount200ResponseLinks {
	this := ListBackupRetentionPoliciesForAccount200ResponseLinks{}
	return &this
}

// NewListBackupRetentionPoliciesForAccount200ResponseLinksWithDefaults instantiates a new ListBackupRetentionPoliciesForAccount200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListBackupRetentionPoliciesForAccount200ResponseLinksWithDefaults() *ListBackupRetentionPoliciesForAccount200ResponseLinks {
	this := ListBackupRetentionPoliciesForAccount200ResponseLinks{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) GetAccount() ListBackupRetentionPoliciesForAccount200ResponseLinksAccount {
	if o == nil || IsNil(o.Account) {
		var ret ListBackupRetentionPoliciesForAccount200ResponseLinksAccount
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) GetAccountOk() (*ListBackupRetentionPoliciesForAccount200ResponseLinksAccount, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given ListBackupRetentionPoliciesForAccount200ResponseLinksAccount and assigns it to the Account field.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) SetAccount(v ListBackupRetentionPoliciesForAccount200ResponseLinksAccount) {
	o.Account = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) GetNext() ListBackupRetentionPoliciesForAccount200ResponseLinksNext {
	if o == nil || IsNil(o.Next) {
		var ret ListBackupRetentionPoliciesForAccount200ResponseLinksNext
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) GetNextOk() (*ListBackupRetentionPoliciesForAccount200ResponseLinksNext, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given ListBackupRetentionPoliciesForAccount200ResponseLinksNext and assigns it to the Next field.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) SetNext(v ListBackupRetentionPoliciesForAccount200ResponseLinksNext) {
	o.Next = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) GetPrev() ListBackupRetentionPoliciesForAccount200ResponseLinksPrev {
	if o == nil || IsNil(o.Prev) {
		var ret ListBackupRetentionPoliciesForAccount200ResponseLinksPrev
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) GetPrevOk() (*ListBackupRetentionPoliciesForAccount200ResponseLinksPrev, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given ListBackupRetentionPoliciesForAccount200ResponseLinksPrev and assigns it to the Prev field.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) SetPrev(v ListBackupRetentionPoliciesForAccount200ResponseLinksPrev) {
	o.Prev = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) GetSelf() ListBackupRetentionPoliciesForAccount200ResponseLinksSelf {
	if o == nil || IsNil(o.Self) {
		var ret ListBackupRetentionPoliciesForAccount200ResponseLinksSelf
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) GetSelfOk() (*ListBackupRetentionPoliciesForAccount200ResponseLinksSelf, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ListBackupRetentionPoliciesForAccount200ResponseLinksSelf and assigns it to the Self field.
func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) SetSelf(v ListBackupRetentionPoliciesForAccount200ResponseLinksSelf) {
	o.Self = &v
}

func (o ListBackupRetentionPoliciesForAccount200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListBackupRetentionPoliciesForAccount200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListBackupRetentionPoliciesForAccount200ResponseLinks) UnmarshalJSON(data []byte) (err error) {
	varListBackupRetentionPoliciesForAccount200ResponseLinks := _ListBackupRetentionPoliciesForAccount200ResponseLinks{}

	err = json.Unmarshal(data, &varListBackupRetentionPoliciesForAccount200ResponseLinks)

	if err != nil {
		return err
	}

	*o = ListBackupRetentionPoliciesForAccount200ResponseLinks(varListBackupRetentionPoliciesForAccount200ResponseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account")
		delete(additionalProperties, "next")
		delete(additionalProperties, "prev")
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListBackupRetentionPoliciesForAccount200ResponseLinks struct {
	value *ListBackupRetentionPoliciesForAccount200ResponseLinks
	isSet bool
}

func (v NullableListBackupRetentionPoliciesForAccount200ResponseLinks) Get() *ListBackupRetentionPoliciesForAccount200ResponseLinks {
	return v.value
}

func (v *NullableListBackupRetentionPoliciesForAccount200ResponseLinks) Set(val *ListBackupRetentionPoliciesForAccount200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableListBackupRetentionPoliciesForAccount200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableListBackupRetentionPoliciesForAccount200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBackupRetentionPoliciesForAccount200ResponseLinks(val *ListBackupRetentionPoliciesForAccount200ResponseLinks) *NullableListBackupRetentionPoliciesForAccount200ResponseLinks {
	return &NullableListBackupRetentionPoliciesForAccount200ResponseLinks{value: val, isSet: true}
}

func (v NullableListBackupRetentionPoliciesForAccount200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBackupRetentionPoliciesForAccount200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


