/*
Deploy API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aptibleapi

import (
	"encoding/json"
)

// checks if the ListServiceSizingPoliciesForAccount200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListServiceSizingPoliciesForAccount200ResponseLinks{}

// ListServiceSizingPoliciesForAccount200ResponseLinks struct for ListServiceSizingPoliciesForAccount200ResponseLinks
type ListServiceSizingPoliciesForAccount200ResponseLinks struct {
	Account *ListServiceSizingPoliciesForAccount200ResponseLinksAccount `json:"account,omitempty"`
	Next *ListServiceSizingPoliciesForAccount200ResponseLinksNext `json:"next,omitempty"`
	Prev *ListServiceSizingPoliciesForAccount200ResponseLinksPrev `json:"prev,omitempty"`
	Self *ListServiceSizingPoliciesForAccount200ResponseLinksSelf `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListServiceSizingPoliciesForAccount200ResponseLinks ListServiceSizingPoliciesForAccount200ResponseLinks

// NewListServiceSizingPoliciesForAccount200ResponseLinks instantiates a new ListServiceSizingPoliciesForAccount200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListServiceSizingPoliciesForAccount200ResponseLinks() *ListServiceSizingPoliciesForAccount200ResponseLinks {
	this := ListServiceSizingPoliciesForAccount200ResponseLinks{}
	return &this
}

// NewListServiceSizingPoliciesForAccount200ResponseLinksWithDefaults instantiates a new ListServiceSizingPoliciesForAccount200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListServiceSizingPoliciesForAccount200ResponseLinksWithDefaults() *ListServiceSizingPoliciesForAccount200ResponseLinks {
	this := ListServiceSizingPoliciesForAccount200ResponseLinks{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) GetAccount() ListServiceSizingPoliciesForAccount200ResponseLinksAccount {
	if o == nil || IsNil(o.Account) {
		var ret ListServiceSizingPoliciesForAccount200ResponseLinksAccount
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) GetAccountOk() (*ListServiceSizingPoliciesForAccount200ResponseLinksAccount, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given ListServiceSizingPoliciesForAccount200ResponseLinksAccount and assigns it to the Account field.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) SetAccount(v ListServiceSizingPoliciesForAccount200ResponseLinksAccount) {
	o.Account = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) GetNext() ListServiceSizingPoliciesForAccount200ResponseLinksNext {
	if o == nil || IsNil(o.Next) {
		var ret ListServiceSizingPoliciesForAccount200ResponseLinksNext
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) GetNextOk() (*ListServiceSizingPoliciesForAccount200ResponseLinksNext, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given ListServiceSizingPoliciesForAccount200ResponseLinksNext and assigns it to the Next field.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) SetNext(v ListServiceSizingPoliciesForAccount200ResponseLinksNext) {
	o.Next = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) GetPrev() ListServiceSizingPoliciesForAccount200ResponseLinksPrev {
	if o == nil || IsNil(o.Prev) {
		var ret ListServiceSizingPoliciesForAccount200ResponseLinksPrev
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) GetPrevOk() (*ListServiceSizingPoliciesForAccount200ResponseLinksPrev, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given ListServiceSizingPoliciesForAccount200ResponseLinksPrev and assigns it to the Prev field.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) SetPrev(v ListServiceSizingPoliciesForAccount200ResponseLinksPrev) {
	o.Prev = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) GetSelf() ListServiceSizingPoliciesForAccount200ResponseLinksSelf {
	if o == nil || IsNil(o.Self) {
		var ret ListServiceSizingPoliciesForAccount200ResponseLinksSelf
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) GetSelfOk() (*ListServiceSizingPoliciesForAccount200ResponseLinksSelf, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ListServiceSizingPoliciesForAccount200ResponseLinksSelf and assigns it to the Self field.
func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) SetSelf(v ListServiceSizingPoliciesForAccount200ResponseLinksSelf) {
	o.Self = &v
}

func (o ListServiceSizingPoliciesForAccount200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListServiceSizingPoliciesForAccount200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListServiceSizingPoliciesForAccount200ResponseLinks) UnmarshalJSON(data []byte) (err error) {
	varListServiceSizingPoliciesForAccount200ResponseLinks := _ListServiceSizingPoliciesForAccount200ResponseLinks{}

	err = json.Unmarshal(data, &varListServiceSizingPoliciesForAccount200ResponseLinks)

	if err != nil {
		return err
	}

	*o = ListServiceSizingPoliciesForAccount200ResponseLinks(varListServiceSizingPoliciesForAccount200ResponseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account")
		delete(additionalProperties, "next")
		delete(additionalProperties, "prev")
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListServiceSizingPoliciesForAccount200ResponseLinks struct {
	value *ListServiceSizingPoliciesForAccount200ResponseLinks
	isSet bool
}

func (v NullableListServiceSizingPoliciesForAccount200ResponseLinks) Get() *ListServiceSizingPoliciesForAccount200ResponseLinks {
	return v.value
}

func (v *NullableListServiceSizingPoliciesForAccount200ResponseLinks) Set(val *ListServiceSizingPoliciesForAccount200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableListServiceSizingPoliciesForAccount200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableListServiceSizingPoliciesForAccount200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListServiceSizingPoliciesForAccount200ResponseLinks(val *ListServiceSizingPoliciesForAccount200ResponseLinks) *NullableListServiceSizingPoliciesForAccount200ResponseLinks {
	return &NullableListServiceSizingPoliciesForAccount200ResponseLinks{value: val, isSet: true}
}

func (v NullableListServiceSizingPoliciesForAccount200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListServiceSizingPoliciesForAccount200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


